import React from 'react';
import TranslateIcon from '@mui/icons-material/Translate';
import {
  Box,
  Button,
  Checkbox,
  IconButton,
  FormControlLabel,
  MenuItem,
  Paper,
  Radio,
  RadioGroup,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Typography,
} from '@mui/material';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { useVirtualRows } from '../../hooks/useVirtualRows';
import { catalogListIssues, type CatalogIssue } from './catalogValidation';
import { useCatalogRemoval } from './useCatalogRemoval';
import { useCatalogTranslations } from './CatalogTranslationsDialog';
import type { CatalogTranslations } from '../../services/itOpsSettings';

// Base type for all enum items. The code is generated by the server from the name and never edited here.
export interface EnumItem {
  code: string;
  label: string;
  deprecated?: boolean;
  translations?: CatalogTranslations;
  localId?: string;
}

// Column definition for the editor
export interface EnumEditorColumn<T extends EnumItem> {
  key: keyof T | string;
  header: string;
  width?: string;
  align?: 'left' | 'center' | 'right';
  render?: (item: T, onChange: (patch: Partial<T>) => void, isLocked: boolean, isFocused: boolean, focusRef: React.RefCallback<HTMLInputElement>) => React.ReactNode;
}

export interface EnumEditorProps<T extends EnumItem> {
  title: string;
  description: string;
  items: T[];
  onChange: (items: T[]) => void;
  columns?: EnumEditorColumn<T>[];
  /** Rows that cannot be edited nor removed (server-managed values). */
  lockedCodes?: string[];
  /** Rows that can be edited and retired but never removed (defaults the server re-adds). */
  protectedCodes?: string[];
  /** Catalog key for usage checks before removal; without it, rows are removed directly. */
  usageList?: string;
  /** Names of this list end up in a comma-separated CSV cell. */
  forbidComma?: boolean;
  hideAddButton?: boolean;
  addButtonLabel?: string;
  onAddRequest?: () => void;
  addRequestToken?: number;
  rowHeight?: number;
  emptyMessage?: string;
}

// Helper to generate local IDs
const makeLocalId = (prefix = 'enum') =>
  `${prefix}-${Math.random().toString(36).slice(2, 9)}-${Date.now().toString(36)}`;

// Ensure items have localIds - returns same reference if no changes needed
const withLocalIds = <T extends EnumItem>(items: T[], prefix = 'enum'): (T & { localId: string })[] => {
  const allHaveIds = items.every((item) => item.localId);
  if (allHaveIds) return items as (T & { localId: string })[];
  return items.map((item) => (item.localId ? item : { ...item, localId: makeLocalId(prefix) })) as (T & { localId: string })[];
};

const issueTextSx = { fontSize: 11, color: 'kanap.text.tertiary', mt: 0.25 } as const;

/** Name column shared by every editor: the visible identity of a value. */
export function nameColumn<T extends EnumItem>(t: TFunction, width = '40%'): EnumEditorColumn<T> {
  return {
    key: 'label',
    header: t('enumEditor.name'),
    width,
    render: (item, onChange, isLocked, isFocused, focusRef) => (
      <TextField
        value={item.label}
        onChange={(e) => onChange({ label: e.target.value } as Partial<T>)}
        size="small"
        fullWidth
        placeholder={t('enumEditor.displayLabel')}
        disabled={isLocked}
        inputRef={isFocused ? focusRef : undefined}
        inputProps={{ 'aria-label': t('enumEditor.name') }}
      />
    ),
  };
}

/** "No longer offered" column: the value stays on existing records and is not proposed any more. */
export function retiredColumn<T extends EnumItem>(t: TFunction, width = '20%'): EnumEditorColumn<T> {
  return {
    key: 'deprecated',
    header: t('enumEditor.noLongerOffered'),
    width,
    render: (item, onChange, isLocked) => (
      <Checkbox
        size="small"
        checked={!!item.deprecated}
        onChange={(e) => onChange({ deprecated: e.target.checked } as Partial<T>)}
        disabled={isLocked}
        inputProps={{ 'aria-label': `${t('enumEditor.noLongerOffered')} ${item.label}` }}
      />
    ),
  };
}

const buildDefaultColumns = <T extends EnumItem>(t: TFunction): EnumEditorColumn<T>[] => [nameColumn<T>(t, '55%'), retiredColumn<T>(t)];

/**
 * Generic editor component for enum/lookup tables.
 * Supports virtual scrolling for large lists and customizable columns.
 */
export function EnumEditor<T extends EnumItem>({
  title,
  description,
  items,
  onChange,
  columns,
  lockedCodes,
  protectedCodes,
  usageList,
  forbidComma,
  hideAddButton,
  addButtonLabel: addButtonLabelProp,
  onAddRequest,
  addRequestToken,
  rowHeight = 52,
  emptyMessage: emptyMessageProp,
}: EnumEditorProps<T>) {
  const { t } = useTranslation('common');
  const addButtonLabel = addButtonLabelProp ?? t('enumEditor.addValue');
  const emptyMessage = emptyMessageProp ?? t('enumEditor.noValues');
  const lockedSet = React.useMemo(
    () => new Set((lockedCodes || []).map((code) => code.toLowerCase())),
    [lockedCodes]
  );
  const protectedSet = React.useMemo(
    () => new Set((protectedCodes || []).map((code) => code.toLowerCase())),
    [protectedCodes]
  );

  const itemsWithIds = React.useMemo(
    () => withLocalIds(items, 'enum'),
    [items]
  );

  const [localItems, setLocalItems] = React.useState<T[]>(itemsWithIds);
  const [focusId, setFocusId] = React.useState<string | null>(null);
  const firstFieldRef = React.useRef<HTMLInputElement | null>(null);
  const lastAddToken = React.useRef<number | undefined>(undefined);
  const pendingCommitRef = React.useRef(false);

  const { containerRef, onScroll, useVirtual, visibleItems, paddingTop, paddingBottom, maxHeight } =
    useVirtualRows({
      items: localItems,
      rowHeight,
    });

  // Sync down from parent - skip if we just committed to avoid loops
  React.useEffect(() => {
    if (pendingCommitRef.current) {
      pendingCommitRef.current = false;
      return;
    }
    setLocalItems(itemsWithIds);
  }, [itemsWithIds]);

  const commitToParent = React.useCallback(
    (next: T[]) => {
      pendingCommitRef.current = true;
      React.startTransition(() => onChange(next));
    },
    [onChange]
  );

  React.useEffect(() => {
    if (focusId && firstFieldRef.current) {
      firstFieldRef.current.focus();
      firstFieldRef.current.select();
      setFocusId(null);
    }
  }, [focusId]);

  const handleUpdate = React.useCallback(
    (localId: string, patch: Partial<T>) => {
      setLocalItems((prev) => {
        const next = prev.map((item) =>
          (item as any).localId === localId ? { ...item, ...patch } : item
        );
        commitToParent(next);
        return next;
      });
    },
    [commitToParent]
  );

  const handleAdd = React.useCallback(() => {
    const newRow = { code: '', label: '', deprecated: false, localId: makeLocalId('enum') } as T;
    setLocalItems((prev) => {
      const next = [newRow, ...prev];
      commitToParent(next);
      return next;
    });
    setFocusId((newRow as any).localId);
  }, [commitToParent]);

  React.useEffect(() => {
    if (addRequestToken === undefined) return;
    if (addRequestToken === lastAddToken.current) return;
    lastAddToken.current = addRequestToken;
    handleAdd();
  }, [addRequestToken, handleAdd]);

  const removeRow = React.useCallback(
    (localId: string) => {
      setLocalItems((prev) => {
        const next = prev.filter((row) => (row as any).localId !== localId);
        commitToParent(next);
        return next;
      });
    },
    [commitToParent]
  );

  // A saved value is removed only when nothing references it; otherwise the dialog offers to retire it.
  const removal = useCatalogRemoval(usageList);
  const translations = useCatalogTranslations();
  const requestRemoval = (item: T & { localId: string }) => removal.requestRemoval({
    name: item.label || item.code,
    key: item.code ? { code: item.code } : null,
    onRemove: () => removeRow(item.localId),
    onRetire: () => handleUpdate(item.localId, { deprecated: true } as Partial<T>),
  });

  const effectiveColumns = React.useMemo(() => columns || buildDefaultColumns<T>(t), [columns, t]);
  const totalColumns = effectiveColumns.length + 1; // +1 for actions column
  const issues = React.useMemo(() => catalogListIssues(localItems, { forbidComma, skipCodes: lockedSet }), [forbidComma, localItems, lockedSet]);
  const issueOf = (item: T): CatalogIssue | undefined => issues.get(localItems.indexOf(item));

  return (
    <Paper variant="outlined" sx={{ p: 2 }}>
      <Stack spacing={1} sx={{ mb: 1 }}>
        <Typography variant="subtitle1" sx={{ fontWeight: 500 }}>
          {title}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {description}
        </Typography>
      </Stack>
      <TableContainer ref={containerRef as any} onScroll={onScroll} sx={{ maxHeight }}>
        <Table size="small" stickyHeader={useVirtual}>
          <TableHead>
            <TableRow>
              {effectiveColumns.map((col) => (
                <TableCell
                  key={String(col.key)}
                  sx={{ width: col.width }}
                  align={col.align || 'left'}
                >
                  {col.header}
                </TableCell>
              ))}
              <TableCell align="right" sx={{ width: '20%' }}>
                {t('labels.actions')}
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {useVirtual && paddingTop > 0 && (
              <TableRow>
                <TableCell colSpan={totalColumns} sx={{ p: 0, height: paddingTop, border: 0 }} />
              </TableRow>
            )}
            {localItems.length === 0 && (
              <TableRow>
                <TableCell colSpan={totalColumns}>
                  <Typography variant="body2" color="text.secondary">
                    {emptyMessage}
                  </Typography>
                </TableCell>
              </TableRow>
            )}
            {visibleItems.map((item, index) => {
              const typedItem = item as T & { localId: string };
              const code = String(typedItem.code || '').toLowerCase();
              const isLocked = lockedSet.has(code);
              const isProtected = !isLocked && protectedSet.has(code);
              const isFocused = typedItem.localId === focusId;
              const issue = issueOf(typedItem);

              return (
                <TableRow key={typedItem.localId || index}>
                  {effectiveColumns.map((col, colIndex) => (
                    <TableCell key={String(col.key)} align={col.align || 'left'} sx={{ verticalAlign: 'top' }}>
                      {col.render ? (
                        col.render(
                          typedItem,
                          (patch) => handleUpdate(typedItem.localId, patch),
                          isLocked,
                          isFocused && colIndex === 0,
                          (el) => {
                            if (isFocused && colIndex === 0) {
                              firstFieldRef.current = el;
                            }
                          }
                        )
                      ) : (
                        String((typedItem as any)[col.key] || '')
                      )}
                      {colIndex === 0 && issue && <Typography sx={issueTextSx}>{t(`enumEditor.${issue}`)}</Typography>}
                    </TableCell>
                  ))}
                  <TableCell align="right" sx={{ verticalAlign: 'top', whiteSpace: 'nowrap' }}>
                    {!isLocked && typedItem.code && (
                      <IconButton size="small" aria-label={`${t('enumEditor.translate')} ${typedItem.label}`} sx={{ color: 'kanap.text.secondary', mr: 0.5 }}
                        onClick={() => translations.openTranslations({ item: typedItem, onSave: (next) => handleUpdate(typedItem.localId, { translations: next } as Partial<T>) })}>
                        <TranslateIcon sx={{ fontSize: 17 }} />
                      </IconButton>
                    )}
                    {isLocked || isProtected ? (
                      <Typography component="span" sx={{ fontSize: 12, color: 'kanap.text.tertiary' }} title={isProtected ? t('enumEditor.protectedHint') : undefined}>
                        {t('enumEditor.locked')}
                      </Typography>
                    ) : (
                      <Button
                        size="small"
                        color="error"
                        onClick={() => void requestRemoval(typedItem)}
                      >
                        {t('enumEditor.remove')}
                      </Button>
                    )}
                  </TableCell>
                </TableRow>
              );
            })}
            {useVirtual && paddingBottom > 0 && (
              <TableRow>
                <TableCell colSpan={totalColumns} sx={{ p: 0, height: paddingBottom, border: 0 }} />
              </TableRow>
            )}
          </TableBody>
        </Table>
      </TableContainer>
      {!hideAddButton && (
        <Box sx={{ mt: 1 }}>
          <Button size="small" onClick={onAddRequest || handleAdd}>
            {addButtonLabel}
          </Button>
        </Box>
      )}
      {removal.dialog}
      {translations.dialog}
    </Paper>
  );
}

// Type-specific editors built on EnumEditor

export interface HostingTypeItem extends EnumItem {
  category?: 'on_prem' | 'cloud';
}

type DerivedEditorProps<T extends EnumItem> = {
  items: T[];
  onChange: (items: T[]) => void;
  hideAddButton?: boolean;
  onAddRequest?: () => void;
  addRequestToken?: number;
  usageList?: string;
  lockedCodes?: string[];
  protectedCodes?: string[];
};

export type HostingTypeEditorProps = DerivedEditorProps<HostingTypeItem>;

const buildHostingTypeColumns = (t: TFunction): EnumEditorColumn<HostingTypeItem>[] => [
  nameColumn<HostingTypeItem>(t, '35%'),
  {
    key: 'category',
    header: t('enumEditor.category'),
    width: '35%',
    render: (item, onChange, isLocked) => (
      <RadioGroup
        row
        value={item.category === 'on_prem' ? 'on_prem' : 'cloud'}
        onChange={(e) => onChange({ category: e.target.value as 'on_prem' | 'cloud' })}
      >
        <FormControlLabel value="on_prem" control={<Radio size="small" />} label={t('enumEditor.onPremColocation')} disabled={isLocked} />
        <FormControlLabel value="cloud" control={<Radio size="small" />} label={t('enumEditor.cloudSaas')} disabled={isLocked} />
      </RadioGroup>
    ),
  },
  retiredColumn<HostingTypeItem>(t, '15%'),
];

export function HostingTypeEditor(props: HostingTypeEditorProps) {
  const { t } = useTranslation('common');
  const columns = React.useMemo(() => buildHostingTypeColumns(t), [t]);
  return (
    <EnumEditor<HostingTypeItem>
      title="Hosting Types"
      description="Location hosting models available when creating Locations (e.g., On-prem, Colocation, Public Cloud, SaaS)."
      columns={columns}
      addButtonLabel="Add hosting type"
      emptyMessage="No hosting types defined."
      {...props}
    />
  );
}

export interface AssetKindItem extends EnumItem {
  is_physical?: boolean;
}

export type AssetKindEditorProps = DerivedEditorProps<AssetKindItem>;

const buildAssetKindColumns = (t: TFunction): EnumEditorColumn<AssetKindItem>[] => [
  nameColumn<AssetKindItem>(t, '45%'),
  {
    key: 'is_physical',
    header: t('enumEditor.physical'),
    width: '15%',
    render: (item, onChange, isLocked) => (
      <Checkbox
        size="small"
        checked={!!item.is_physical}
        onChange={(e) => onChange({ is_physical: e.target.checked })}
        disabled={isLocked}
        inputProps={{ 'aria-label': `${t('enumEditor.physical')} ${item.label}` }}
      />
    ),
  },
  retiredColumn<AssetKindItem>(t, '20%'),
];

export function AssetKindEditor(props: AssetKindEditorProps) {
  const { t } = useTranslation('common');
  const columns = React.useMemo(() => buildAssetKindColumns(t), [t]);
  return (
    <EnumEditor<AssetKindItem>
      title="Asset Types"
      description="Logical types for servers and infrastructure assets. Physical assets can track hardware and support information."
      columns={columns}
      addButtonLabel="Add asset type"
      emptyMessage="No asset types defined."
      {...props}
    />
  );
}

type GraphTier = 'top' | 'upper' | 'center' | 'lower' | 'bottom';

const GRAPH_TIER_OPTIONS: Array<{ value: GraphTier; label: string }> = [
  { value: 'top', label: 'Top' },
  { value: 'upper', label: 'Upper' },
  { value: 'center', label: 'Center' },
  { value: 'lower', label: 'Lower' },
  { value: 'bottom', label: 'Bottom' },
];

export interface ServerRoleItem extends EnumItem {
  graph_tier?: GraphTier;
}

export interface EntityItem extends EnumItem {
  graph_tier?: GraphTier;
}

const buildTieredColumns = <T extends EnumItem & { graph_tier?: GraphTier }>(
  t: TFunction,
  defaultTier: GraphTier,
): EnumEditorColumn<T>[] => [
  nameColumn<T>(t, '40%'),
  {
    key: 'graph_tier',
    header: t('enumEditor.graphTier'),
    width: '25%',
    render: (item, onChange, isLocked) => (
      <TextField
        select
        value={item.graph_tier || defaultTier}
        onChange={(e) => onChange({ graph_tier: e.target.value as GraphTier } as Partial<T>)}
        size="small"
        fullWidth
        disabled={isLocked}
      >
        {GRAPH_TIER_OPTIONS.map((opt) => (
          <MenuItem key={opt.value} value={opt.value}>
            {opt.label}
          </MenuItem>
        ))}
      </TextField>
    ),
  },
  retiredColumn<T>(t, '15%'),
];

export type ServerRoleEditorProps = DerivedEditorProps<ServerRoleItem>;

export function ServerRoleEditor(props: ServerRoleEditorProps) {
  const { t } = useTranslation('common');
  const columns = React.useMemo(() => buildTieredColumns<ServerRoleItem>(t, 'center'), [t]);
  return (
    <EnumEditor<ServerRoleItem>
      title="Server Roles"
      description="Roles assigned to servers when linking app instances. Graph tier influences connection map placement."
      columns={columns}
      addButtonLabel="Add server role"
      emptyMessage="No server roles defined."
      {...props}
    />
  );
}

export type EntityEditorProps = DerivedEditorProps<EntityItem>;

export function EntityEditor(props: EntityEditorProps) {
  const { t } = useTranslation('common');
  const columns = React.useMemo(() => buildTieredColumns<EntityItem>(t, 'top'), [t]);
  return (
    <EnumEditor<EntityItem>
      title="Entities"
      description="Endpoints used in connections and maps. Graph tier influences default map placement."
      columns={columns}
      addButtonLabel="Add entity"
      emptyMessage="No entities defined."
      {...props}
    />
  );
}

export default EnumEditor;
