import { AiEntityFilterRegistry } from '../ai-filter.types';

export const applicationsRegistry: AiEntityFilterRegistry = {
  entityType: 'applications',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Application enabled or disabled status.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    lifecycle: {
      ai: 'lifecycle',
      grid: 'lifecycle',
      type: 'set',
      description: 'Application lifecycle.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    criticality: {
      ai: 'criticality',
      grid: 'criticality',
      type: 'set',
      description: 'Application criticality.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    category: {
      ai: 'category',
      grid: 'category',
      type: 'set',
      description: 'Application category.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    hosting_model: {
      ai: 'hosting_model',
      grid: 'hosting_model',
      type: 'set',
      description: 'Hosting model.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    data_class: {
      ai: 'data_class',
      grid: 'data_class',
      type: 'set',
      description: 'Data classification.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    supplier: {
      ai: 'supplier',
      grid: 'supplier_name',
      type: 'set',
      description: 'Supplier name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
  },
  sortFields: {
    label: 'name',
    status: 'status',
    lifecycle: 'lifecycle',
    criticality: 'criticality',
    category: 'category',
    hosting_model: 'hosting_model',
    data_class: 'data_class',
    supplier: 'supplier_name',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'applications',
    alias: 'a',
    groupFields: {
      status: { expression: 'a.status' },
      lifecycle: { expression: 'a.lifecycle' },
      criticality: { expression: 'a.criticality' },
      category: { expression: 'a.category' },
      hosting_model: { expression: 'a.hosting_model' },
      data_class: { expression: 'a.data_class' },
      supplier: {
        expression: 's.name',
        joins: [
          `LEFT JOIN suppliers s ON s.id = a.supplier_id AND s.tenant_id = a.tenant_id`,
        ],
      },
    },
  },
};
