import { classificationSqlExpressions } from '../../../it-ops-settings/classification-sql';
const classificationSql = classificationSqlExpressions('a');
import { AiEntityFilterRegistry } from '../ai-filter.types';

export const applicationsRegistry: AiEntityFilterRegistry = {
  entityType: 'applications',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Application enabled or disabled status.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    sequential_id: {
      ai: 'sequential_id',
      grid: 'sequential_id',
      type: 'text',
      description: 'Application reference such as APP-123.',
      sortable: true,
      groupable: false,
    },
    lifecycle: {
      ai: 'lifecycle',
      grid: 'lifecycle',
      type: 'set',
      description: 'Application lifecycle.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    editor: {
      ai: 'editor',
      grid: 'editor',
      type: 'set',
      description: 'Application editor or publisher.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    environment: {
      ai: 'environment',
      grid: 'environment',
      type: 'set',
      description: 'Legacy primary application environment.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    environments: {
      ai: 'environments',
      grid: 'environments',
      type: 'set',
      description: 'Environments from application instances.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    hosting_types: {
      ai: 'hosting_types',
      grid: 'hosting_types',
      type: 'set',
      description: 'Hosting types inferred from assigned assets and their locations.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    criticality: {
      ai: 'criticality',
      grid: 'criticality',
      type: 'set',
      description: 'Derived business criticality code, computed from business_mtd_minutes. Use get_application_classification_catalog for tenant definitions and ranks. Null means unclassified.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
      aliases: ['business_criticality', 'criticite_metier'],
      acceptedValueKind: 'classification_code_from_application_catalog',
    },
    business_criticality_rank: {
      ai: 'business_criticality_rank', grid: 'business_criticality_rank', type: 'number',
      description: 'Tenant-defined severity rank of business criticality. Null is not a severity.',
      sortable: true, groupable: false, aggregable: true,
      aliases: ['business_rank', 'rang_criticite_metier'],
    },
    business_mtd_minutes: {
      ai: 'business_mtd_minutes', grid: 'business_mtd_minutes', type: 'number',
      description: 'Maximum tolerable business interruption (DMIA/MTD) in whole minutes. Null means unassessed.',
      sortable: true, groupable: false, aggregable: true,
      aliases: ['business_mtd', 'mtd_minutes', 'dmia_minutes', 'dmia'],
      examples: ['{"op":"lte","value":1440}'],
    },
    cyber_criticality: {
      ai: 'cyber_criticality', grid: 'cyber_criticality', type: 'set',
      description: 'Manual cyber criticality code. Use get_application_classification_catalog for definitions and ranks. Null means unclassified.',
      dynamic: true, discoverable: true, sortable: true, groupable: true,
      aliases: ['cyber', 'criticite_cyber'], acceptedValueKind: 'classification_code_from_application_catalog',
    },
    cyber_criticality_rank: {
      ai: 'cyber_criticality_rank', grid: 'cyber_criticality_rank', type: 'number',
      description: 'Tenant-defined cyber severity rank, including deprecated historical levels. Null is not a severity.',
      sortable: true, groupable: false, aggregable: true,
      aliases: ['cyber_rank', 'rang_criticite_cyber'],
    },
    recovery_wave: {
      ai: 'recovery_wave', grid: 'recovery_wave', type: 'set',
      description: 'Manual recovery wave code. Use get_application_classification_catalog for definitions and order. Null means unassigned.',
      dynamic: true, discoverable: true, sortable: true, groupable: true,
      aliases: ['wave', 'vague_reprise'], acceptedValueKind: 'classification_code_from_application_catalog',
    },
    recovery_wave_order: {
      ai: 'recovery_wave_order', grid: 'recovery_wave_order', type: 'number',
      description: 'Tenant-defined recovery wave order. Null means no assigned wave.',
      sortable: true, groupable: false, aggregable: true,
      aliases: ['wave_order', 'ordre_vague_reprise'],
    },
    rto_minutes: {
      ai: 'rto_minutes', grid: 'rto_minutes', type: 'number',
      description: 'Recovery time objective in whole minutes. Null means unspecified.',
      sortable: true, groupable: false, aggregable: true, aliases: ['rto'],
    },
    rpo_minutes: {
      ai: 'rpo_minutes', grid: 'rpo_minutes', type: 'number',
      description: 'Recovery point objective in whole minutes. Zero means no data loss is acceptable; null means unspecified.',
      sortable: true, groupable: false, aggregable: true, aliases: ['rpo'],
    },
    classification_review_state: {
      ai: 'classification_review_state', grid: 'classification_review_state', type: 'set',
      description: 'Human classification review state. Classification mutations never mark an application reviewed implicitly.',
      values: ['incomplete', 'stale', 'reviewed'], discoverable: true, sortable: true, groupable: true,
      aliases: ['review_state', 'etat_revue_classification'],
    },
    classification_reviewed_at: {
      ai: 'classification_reviewed_at', grid: 'classification_reviewed_at', type: 'date',
      description: 'Server timestamp of the latest human classification review, or null when never reviewed.',
      sortable: true, groupable: false, aggregable: true,
      aliases: ['reviewed_at', 'date_revue_classification'],
    },
    category: {
      ai: 'category',
      grid: 'category',
      type: 'set',
      description: 'Application category values observed on existing application records. Use tenant IT ops settings, not this observed list, as the create/update catalog.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    hosting_model: {
      ai: 'hosting_model',
      grid: 'hosting_model',
      type: 'set',
      description: 'Hosting model.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    data_class: {
      ai: 'data_class',
      grid: 'data_class',
      type: 'set',
      description: 'Data confidentiality classification code. Use get_application_classification_catalog for definitions and ranks. Null means unclassified.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
      aliases: ['confidentiality', 'data_confidentiality', 'confidentialite'],
      acceptedValueKind: 'classification_code_from_application_catalog',
    },
    data_class_rank: {
      ai: 'data_class_rank', grid: 'data_class_rank', type: 'number',
      description: 'Tenant-defined confidentiality rank, including deprecated historical levels. Null is not a rank.',
      sortable: true, groupable: false, aggregable: true,
      aliases: ['confidentiality_rank', 'rang_confidentialite'],
    },
    external_facing: {
      ai: 'external_facing',
      grid: 'external_facing',
      type: 'set',
      description: 'Whether the application is externally facing.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    is_suite: {
      ai: 'is_suite',
      grid: 'is_suite',
      type: 'set',
      description: 'Whether the application is a suite/container application.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    sso_enabled: {
      ai: 'sso_enabled',
      grid: 'sso_enabled',
      type: 'set',
      description: 'Whether SSO is enabled.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    mfa_supported: {
      ai: 'mfa_supported',
      grid: 'mfa_supported',
      type: 'set',
      description: 'Whether MFA is supported.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    etl_enabled: {
      ai: 'etl_enabled',
      grid: 'etl_enabled',
      type: 'set',
      description: 'Whether ETL processing is enabled.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    contains_pii: {
      ai: 'contains_pii',
      grid: 'contains_pii',
      type: 'set',
      description: 'Whether the application contains PII.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    users_mode: {
      ai: 'users_mode',
      grid: 'users_mode',
      type: 'set',
      description: 'How application user count is derived.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    users_year: {
      ai: 'users_year',
      grid: 'users_year',
      type: 'number',
      description: 'Metric year used for derived application users.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    users_override: {
      ai: 'users_override',
      grid: 'users_override',
      type: 'number',
      description: 'Manual application user count override.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    derived_total_users: {
      ai: 'derived_total_users',
      grid: 'derived_total_users',
      type: 'number',
      description: 'Computed total users for the configured user mode and year.',
      sortable: false,
      groupable: false,
    },
    data_residency: {
      ai: 'data_residency',
      grid: 'data_residency',
      type: 'set',
      description: 'Data residency country codes.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    spend_count: {
      ai: 'spend_count',
      grid: 'spend_count',
      type: 'number',
      description: 'Number of linked spend items.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    capex_count: {
      ai: 'capex_count',
      grid: 'capex_count',
      type: 'number',
      description: 'Number of linked CAPEX items.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    contracts_count: {
      ai: 'contracts_count',
      grid: 'contracts_count',
      type: 'number',
      description: 'Number of linked contracts.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    suites_count: {
      ai: 'suites_count',
      grid: 'suites_count',
      type: 'number',
      description: 'Number of suites this application belongs to.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    components_count: {
      ai: 'components_count',
      grid: 'components_count',
      type: 'number',
      description: 'Number of components in this suite application.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    supplier: {
      ai: 'supplier',
      grid: 'supplier_name',
      type: 'set',
      description: 'Supplier name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    it_owner: {
      ai: 'it_owner',
      grid: 'owners_it',
      type: 'set',
      description: 'IT owner display names.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    business_owner: {
      ai: 'business_owner',
      grid: 'owners_business',
      type: 'set',
      description: 'Business owner display names.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    linked_project: {
      ai: 'linked_project',
      grid: 'linked_project_name',
      type: 'text',
      description: 'Linked project name or reference.',
      sortable: false,
      groupable: false,
    },
  },
  sortFields: {
    label: 'name',
    sequential_id: 'sequential_id',
    status: 'status',
    lifecycle: 'lifecycle',
    criticality: 'criticality',
    business_criticality_rank: 'business_criticality_rank',
    business_mtd_minutes: 'business_mtd_minutes',
    cyber_criticality: 'cyber_criticality',
    cyber_criticality_rank: 'cyber_criticality_rank',
    recovery_wave: 'recovery_wave',
    recovery_wave_order: 'recovery_wave_order',
    rto_minutes: 'rto_minutes',
    rpo_minutes: 'rpo_minutes',
    classification_review_state: 'classification_review_state',
    classification_reviewed_at: 'classification_reviewed_at',
    category: 'category',
    editor: 'editor',
    environment: 'environment',
    hosting_model: 'hosting_model',
    data_class: 'data_class',
    data_class_rank: 'data_class_rank',
    external_facing: 'external_facing',
    is_suite: 'is_suite',
    sso_enabled: 'sso_enabled',
    mfa_supported: 'mfa_supported',
    etl_enabled: 'etl_enabled',
    contains_pii: 'contains_pii',
    users_mode: 'users_mode',
    users_year: 'users_year',
    users_override: 'users_override',
    spend_count: 'spend_count',
    capex_count: 'capex_count',
    contracts_count: 'contracts_count',
    suites_count: 'suites_count',
    components_count: 'components_count',
    supplier: 'supplier_name',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'applications',
    alias: 'a',
    groupFields: {
      status: { expression: 'a.status' },
      lifecycle: { expression: 'a.lifecycle' },
      criticality: { expression: 'a.criticality' },
      cyber_criticality: { expression: 'a.cyber_criticality' },
      recovery_wave: { expression: 'a.recovery_wave' },
      classification_review_state: { expression: classificationSql.classification_review_state },
      category: { expression: 'a.category' },
      editor: { expression: 'a.editor' },
      environment: { expression: 'a.environment' },
      hosting_model: { expression: 'a.hosting_model' },
      data_class: { expression: 'a.data_class' },
      external_facing: { expression: `CASE WHEN COALESCE(a.external_facing, false) THEN 'true' ELSE 'false' END` },
      is_suite: { expression: `CASE WHEN COALESCE(a.is_suite, false) THEN 'true' ELSE 'false' END` },
      sso_enabled: { expression: `CASE WHEN COALESCE(a.sso_enabled, false) THEN 'true' ELSE 'false' END` },
      mfa_supported: { expression: `CASE WHEN COALESCE(a.mfa_supported, false) THEN 'true' ELSE 'false' END` },
      etl_enabled: { expression: `CASE WHEN COALESCE(a.etl_enabled, false) THEN 'true' ELSE 'false' END` },
      contains_pii: { expression: `CASE WHEN COALESCE(a.contains_pii, false) THEN 'true' ELSE 'false' END` },
      users_mode: { expression: 'a.users_mode' },
      supplier: {
        expression: 's.name',
        joins: [
          `LEFT JOIN suppliers s ON s.id = a.supplier_id AND s.tenant_id = a.tenant_id`,
        ],
      },
      business_owner: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_biz.first_name, ' ', u_biz.last_name)), ''), u_biz.email)`,
        joins: [
          `LEFT JOIN application_owners ao_biz ON ao_biz.application_id = a.id AND ao_biz.tenant_id = a.tenant_id AND ao_biz.owner_type = 'business'`,
          `LEFT JOIN users u_biz ON u_biz.id = ao_biz.user_id AND u_biz.tenant_id = a.tenant_id`,
        ],
      },
      it_owner: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_it.first_name, ' ', u_it.last_name)), ''), u_it.email)`,
        joins: [
          `LEFT JOIN application_owners ao_it ON ao_it.application_id = a.id AND ao_it.tenant_id = a.tenant_id AND ao_it.owner_type = 'it'`,
          `LEFT JOIN users u_it ON u_it.id = ao_it.user_id AND u_it.tenant_id = a.tenant_id`,
        ],
      },
      data_residency: {
        expression: 'dr.country_iso',
        joins: [
          `LEFT JOIN application_data_residency dr ON dr.application_id = a.id AND dr.tenant_id = a.tenant_id`,
        ],
      },
      environments: {
        expression: 'ai.environment',
        joins: [
          `LEFT JOIN app_instances ai ON ai.application_id = a.id AND ai.tenant_id = a.tenant_id`,
        ],
      },
      hosting_types: {
        expression: 'l.hosting_type',
        joins: [
          `LEFT JOIN app_instances ai_host ON ai_host.application_id = a.id AND ai_host.tenant_id = a.tenant_id`,
          `LEFT JOIN app_asset_assignments aaa_host ON aaa_host.app_instance_id = ai_host.id AND aaa_host.tenant_id = a.tenant_id`,
          `LEFT JOIN assets ast_host ON ast_host.id = aaa_host.asset_id AND ast_host.tenant_id = a.tenant_id`,
          `LEFT JOIN locations l ON l.id = ast_host.location_id AND l.tenant_id = a.tenant_id`,
        ],
      },
    },
    metricFields: {
      ...Object.fromEntries(['business_criticality_rank', 'cyber_criticality_rank', 'data_class_rank', 'recovery_wave_order'].map((field) => [field, { expression: classificationSql[field], type: 'number' as const }])),
      users_year: { expression: 'a.users_year', type: 'number' },
      users_override: { expression: 'a.users_override', type: 'number' },
      business_mtd_minutes: { expression: 'a.business_mtd_minutes', type: 'number' },
      rto_minutes: { expression: 'a.rto_minutes', type: 'number' },
      rpo_minutes: { expression: 'a.rpo_minutes', type: 'number' },
      classification_reviewed_at: { expression: classificationSql.classification_reviewed_at, type: 'date' },
      spend_count: {
        expression: `(SELECT COUNT(*) FROM application_spend_items l WHERE l.application_id = a.id AND l.tenant_id = a.tenant_id)`,
        type: 'number',
      },
      capex_count: {
        expression: `(SELECT COUNT(*) FROM application_capex_items l WHERE l.application_id = a.id AND l.tenant_id = a.tenant_id)`,
        type: 'number',
      },
      contracts_count: {
        expression: `(SELECT COUNT(*) FROM application_contracts l WHERE l.application_id = a.id AND l.tenant_id = a.tenant_id)`,
        type: 'number',
      },
      suites_count: {
        expression: `(SELECT COUNT(*) FROM application_suites l WHERE l.application_id = a.id AND l.tenant_id = a.tenant_id)`,
        type: 'number',
      },
      components_count: {
        expression: `(SELECT COUNT(*) FROM application_suites l WHERE l.suite_id = a.id AND l.tenant_id = a.tenant_id)`,
        type: 'number',
      },
    },
  },
};
