import { AiEntityFilterRegistry } from '../ai-filter.types';

export const applicationsRegistry: AiEntityFilterRegistry = {
  entityType: 'applications',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Application enabled or disabled status.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    lifecycle: {
      ai: 'lifecycle',
      grid: 'lifecycle',
      type: 'set',
      description: 'Application lifecycle.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    criticality: {
      ai: 'criticality',
      grid: 'criticality',
      type: 'set',
      description: 'Application criticality.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    category: {
      ai: 'category',
      grid: 'category',
      type: 'set',
      description: 'Application category.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    hosting_model: {
      ai: 'hosting_model',
      grid: 'hosting_model',
      type: 'set',
      description: 'Hosting model.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    data_class: {
      ai: 'data_class',
      grid: 'data_class',
      type: 'set',
      description: 'Data classification.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    supplier: {
      ai: 'supplier',
      grid: 'supplier_name',
      type: 'set',
      description: 'Supplier name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    it_owner: {
      ai: 'it_owner',
      grid: 'owners_it',
      type: 'set',
      description: 'IT owner display names.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    business_owner: {
      ai: 'business_owner',
      grid: 'owners_business',
      type: 'set',
      description: 'Business owner display names.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    linked_project: {
      ai: 'linked_project',
      grid: 'linked_project_name',
      type: 'text',
      description: 'Linked project name or reference.',
      sortable: false,
      groupable: false,
    },
  },
  sortFields: {
    label: 'name',
    status: 'status',
    lifecycle: 'lifecycle',
    criticality: 'criticality',
    category: 'category',
    hosting_model: 'hosting_model',
    data_class: 'data_class',
    supplier: 'supplier_name',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'applications',
    alias: 'a',
    groupFields: {
      status: { expression: 'a.status' },
      lifecycle: { expression: 'a.lifecycle' },
      criticality: { expression: 'a.criticality' },
      category: { expression: 'a.category' },
      hosting_model: { expression: 'a.hosting_model' },
      data_class: { expression: 'a.data_class' },
      supplier: {
        expression: 's.name',
        joins: [
          `LEFT JOIN suppliers s ON s.id = a.supplier_id AND s.tenant_id = a.tenant_id`,
        ],
      },
      business_owner: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_biz.first_name, ' ', u_biz.last_name)), ''), u_biz.email)`,
        joins: [
          `LEFT JOIN application_owners ao_biz ON ao_biz.application_id = a.id AND ao_biz.tenant_id = a.tenant_id AND ao_biz.owner_type = 'business'`,
          `LEFT JOIN users u_biz ON u_biz.id = ao_biz.user_id AND u_biz.tenant_id = a.tenant_id`,
        ],
      },
      it_owner: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_it.first_name, ' ', u_it.last_name)), ''), u_it.email)`,
        joins: [
          `LEFT JOIN application_owners ao_it ON ao_it.application_id = a.id AND ao_it.tenant_id = a.tenant_id AND ao_it.owner_type = 'it'`,
          `LEFT JOIN users u_it ON u_it.id = ao_it.user_id AND u_it.tenant_id = a.tenant_id`,
        ],
      },
    },
  },
};
