import { AiEntityFilterRegistry } from '../ai-filter.types';

export const assetsRegistry: AiEntityFilterRegistry = {
  entityType: 'assets',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Asset status.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    kind: {
      ai: 'kind',
      grid: 'kind',
      type: 'set',
      description: 'Asset kind.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    environment: {
      ai: 'environment',
      grid: 'environment',
      type: 'set',
      description: 'Asset environment.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    provider: {
      ai: 'provider',
      grid: 'provider',
      type: 'set',
      description: 'Provider name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    os: {
      ai: 'os',
      grid: 'operating_system',
      type: 'set',
      description: 'Operating system.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    location: {
      ai: 'location',
      grid: 'location_name',
      type: 'set',
      description: 'Location name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    sub_location: {
      ai: 'sub_location',
      grid: 'sub_location_name',
      type: 'text',
      description: 'Sub-location name within the location (for example building, room, or rack).',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    hostname: {
      ai: 'hostname',
      grid: 'hostname',
      type: 'text',
      description: 'Asset hostname.',
      sortable: true,
      groupable: false,
    },
    fqdn: {
      ai: 'fqdn',
      grid: 'fqdn',
      type: 'text',
      description: 'Asset fully qualified domain name.',
      sortable: true,
      groupable: false,
    },
  },
  sortFields: {
    label: 'name',
    status: 'status',
    kind: 'kind',
    environment: 'environment',
    provider: 'provider',
    os: 'operating_system',
    location: 'location_name',
    sub_location: 'sub_location_name',
    hostname: 'hostname',
    fqdn: 'fqdn',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'assets',
    alias: 'a',
    groupFields: {
      status: { expression: 'a.status' },
      kind: { expression: 'a.kind' },
      environment: { expression: 'a.environment' },
      provider: { expression: 'a.provider' },
      os: { expression: 'a.operating_system' },
      location: {
        expression: 'l.name',
        joins: [
          `LEFT JOIN locations l ON l.id = a.location_id AND l.tenant_id = a.tenant_id`,
        ],
      },
      sub_location: {
        expression: 'sl.name',
        joins: [
          `LEFT JOIN location_sub_items sl ON sl.id = a.sub_location_id AND sl.tenant_id = a.tenant_id`,
        ],
      },
    },
  },
};
