import { AiEntityFilterRegistry } from '../ai-filter.types';

export const assetsRegistry: AiEntityFilterRegistry = {
  entityType: 'assets',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Asset status.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    kind: {
      ai: 'kind',
      grid: 'kind',
      type: 'set',
      description: 'Asset kind.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    asset_reference: {
      ai: 'asset_reference',
      grid: 'asset_reference',
      type: 'set',
      description: 'Asset reference or inventory identifier.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    environment: {
      ai: 'environment',
      grid: 'environment',
      type: 'set',
      description: 'Asset environment.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    provider: {
      ai: 'provider',
      grid: 'provider',
      type: 'set',
      description: 'Provider name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    region: {
      ai: 'region',
      grid: 'region',
      type: 'set',
      description: 'Cloud or infrastructure region.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    zone: {
      ai: 'zone',
      grid: 'zone',
      type: 'set',
      description: 'Cloud or infrastructure availability zone.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    os: {
      ai: 'os',
      grid: 'operating_system',
      type: 'set',
      description: 'Operating system.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    hosting_type: {
      ai: 'hosting_type',
      grid: 'hosting_type',
      type: 'set',
      description: 'Hosting type of the asset location.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    location: {
      ai: 'location',
      grid: 'location_name',
      type: 'set',
      description: 'Location name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    sub_location: {
      ai: 'sub_location',
      grid: 'sub_location_name',
      type: 'text',
      description: 'Sub-location name within the location (for example building, room, or rack).',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    hostname: {
      ai: 'hostname',
      grid: 'hostname',
      type: 'text',
      description: 'Asset hostname.',
      sortable: true,
      groupable: false,
    },
    fqdn: {
      ai: 'fqdn',
      grid: 'fqdn',
      type: 'text',
      description: 'Asset fully qualified domain name.',
      sortable: true,
      groupable: false,
    },
    network_segment: {
      ai: 'network_segment',
      grid: 'network_segment',
      type: 'set',
      description: 'Network segment from the first IP address entry.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    cluster: {
      ai: 'cluster',
      grid: 'cluster',
      type: 'set',
      description: 'Cluster this asset belongs to.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    is_cluster: {
      ai: 'is_cluster',
      grid: 'is_cluster',
      type: 'set',
      description: 'Whether the asset is a cluster/container asset.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    assignments_count: {
      ai: 'assignments_count',
      grid: 'assignments_count',
      type: 'number',
      description: 'Number of application instance assignments for the asset.',
      sortable: false,
      groupable: false,
      aggregable: true,
    },
  },
  sortFields: {
    label: 'name',
    status: 'status',
    kind: 'kind',
    asset_reference: 'asset_reference',
    environment: 'environment',
    provider: 'provider',
    region: 'region',
    zone: 'zone',
    os: 'operating_system',
    location: 'location_name',
    hosting_type: 'hosting_type',
    sub_location: 'sub_location_name',
    hostname: 'hostname',
    fqdn: 'fqdn',
    cluster: 'cluster',
    is_cluster: 'is_cluster',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'assets',
    alias: 'a',
    groupFields: {
      status: { expression: 'a.status' },
      kind: { expression: 'a.kind' },
      asset_reference: { expression: 'a.asset_reference' },
      environment: { expression: 'a.environment' },
      provider: { expression: 'a.provider' },
      region: { expression: 'a.region' },
      zone: { expression: 'a.zone' },
      os: { expression: 'a.operating_system' },
      hosting_type: {
        expression: 'l.hosting_type',
        joins: [
          `LEFT JOIN locations l ON l.id = a.location_id AND l.tenant_id = a.tenant_id`,
        ],
      },
      location: {
        expression: 'l.name',
        joins: [
          `LEFT JOIN locations l ON l.id = a.location_id AND l.tenant_id = a.tenant_id`,
        ],
      },
      sub_location: {
        expression: 'sl.name',
        joins: [
          `LEFT JOIN location_sub_items sl ON sl.id = a.sub_location_id AND sl.tenant_id = a.tenant_id`,
        ],
      },
      network_segment: { expression: `a.ip_addresses->0->>'network_segment'` },
      cluster: {
        expression: 'cluster_asset.name',
        joins: [
          `LEFT JOIN asset_cluster_members acm ON acm.asset_id = a.id AND acm.tenant_id = a.tenant_id`,
          `LEFT JOIN assets cluster_asset ON cluster_asset.id = acm.cluster_id AND cluster_asset.tenant_id = a.tenant_id`,
        ],
      },
      is_cluster: { expression: `CASE WHEN COALESCE(a.is_cluster, false) THEN 'true' ELSE 'false' END` },
    },
    metricFields: {
      assignments_count: {
        expression: `(SELECT COUNT(*) FROM app_asset_assignments aaa WHERE aaa.asset_id = a.id AND aaa.tenant_id = a.tenant_id)`,
        type: 'number',
      },
    },
  },
};
