import { AiEntityFilterRegistry } from '../ai-filter.types';

export const capexItemsRegistry: AiEntityFilterRegistry = {
  entityType: 'capex_items',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'CAPEX item lifecycle status.',
      values: ['enabled', 'disabled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    ppe_type: {
      ai: 'ppe_type',
      grid: 'ppe_type',
      type: 'set',
      description: 'CAPEX PPE type.',
      values: ['hardware', 'software'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    investment_type: {
      ai: 'investment_type',
      grid: 'investment_type',
      type: 'set',
      description: 'CAPEX investment type.',
      values: ['replacement', 'capacity', 'productivity', 'security', 'conformity', 'business_growth', 'other'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    priority: {
      ai: 'priority',
      grid: 'priority',
      type: 'set',
      description: 'CAPEX priority.',
      values: ['mandatory', 'high', 'medium', 'low'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    currency: {
      ai: 'currency',
      grid: 'currency',
      type: 'set',
      description: 'CAPEX item currency.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    paying_company: {
      ai: 'paying_company',
      grid: 'company_name',
      type: 'set',
      description: 'Paying company name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    effective_start: {
      ai: 'effective_start',
      grid: 'effective_start',
      type: 'date',
      description: 'Effective start date.',
      sortable: true,
      groupable: false,
    },
    effective_end: {
      ai: 'effective_end',
      grid: 'effective_end',
      type: 'date',
      description: 'Effective end date.',
      sortable: true,
      groupable: false,
    },
    y_budget: {
      ai: 'y_budget',
      grid: 'yBudget',
      type: 'number',
      description: 'Current-year CAPEX budget total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_actual: {
      ai: 'y_actual',
      grid: 'yFollowUp',
      type: 'number',
      description: 'Current-year CAPEX actual/follow-up total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_landing: {
      ai: 'y_landing',
      grid: 'yLanding',
      type: 'number',
      description: 'Current-year CAPEX landing total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_plus1_budget: {
      ai: 'y_plus1_budget',
      grid: 'yPlus1Budget',
      type: 'number',
      description: 'Next-year CAPEX budget total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_minus1_landing: {
      ai: 'y_minus1_landing',
      grid: 'yMinus1Landing',
      type: 'number',
      description: 'Previous-year CAPEX landing total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
  },
  sortFields: {
    label: 'description',
    status: 'status',
    ppe_type: 'ppe_type',
    investment_type: 'investment_type',
    priority: 'priority',
    currency: 'currency',
    paying_company: 'company_name',
    effective_start: 'effective_start',
    effective_end: 'effective_end',
    y_budget: 'yBudget',
    y_actual: 'yFollowUp',
    y_landing: 'yLanding',
    y_plus1_budget: 'yPlus1Budget',
    y_minus1_landing: 'yMinus1Landing',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'capex_items',
    alias: 'ci',
    groupFields: {
      status: { expression: 'ci.status' },
      ppe_type: { expression: 'ci.ppe_type' },
      investment_type: { expression: 'ci.investment_type' },
      priority: { expression: 'ci.priority' },
      currency: { expression: 'ci.currency' },
      paying_company: {
        expression: 'co.name',
        joins: ['LEFT JOIN companies co ON co.id = ci.paying_company_id AND co.tenant_id = ci.tenant_id'],
      },
    },
  },
};
