import { AiEntityFilterRegistry } from '../ai-filter.types';

export const contractsRegistry: AiEntityFilterRegistry = {
  entityType: 'contracts',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Contract lifecycle status.',
      values: ['enabled', 'disabled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    currency: {
      ai: 'currency',
      grid: 'currency',
      type: 'set',
      description: 'Contract currency.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    billing_frequency: {
      ai: 'billing_frequency',
      grid: 'billing_frequency',
      type: 'set',
      description: 'Contract billing frequency.',
      values: ['monthly', 'quarterly', 'annual', 'other'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    start_date: {
      ai: 'start_date',
      grid: 'start_date',
      type: 'date',
      description: 'Contract start date.',
      sortable: true,
      groupable: false,
    },
    yearly_amount: {
      ai: 'yearly_amount',
      grid: 'yearly_amount_at_signature',
      type: 'number',
      description: 'Yearly amount at signature.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
  },
  sortFields: {
    label: 'name',
    status: 'status',
    currency: 'currency',
    billing_frequency: 'billing_frequency',
    start_date: 'start_date',
    end_date: 'end_date',
    cancellation_deadline: 'cancellation_deadline',
    yearly_amount: 'yearly_amount_at_signature',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'contracts',
    alias: 'c',
    groupFields: {
      status: { expression: 'c.status' },
      currency: { expression: 'c.currency' },
      billing_frequency: { expression: 'c.billing_frequency' },
    },
  },
};
