import { AiEntityFilterRegistry } from '../ai-filter.types';

export const contractsRegistry: AiEntityFilterRegistry = {
  entityType: 'contracts',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Contract lifecycle status.',
      values: ['enabled', 'disabled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    currency: {
      ai: 'currency',
      grid: 'currency',
      type: 'set',
      description: 'Contract currency.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    supplier: {
      ai: 'supplier',
      grid: 'supplier_name',
      type: 'set',
      description: 'Contract supplier name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    company: {
      ai: 'company',
      grid: 'company_name',
      type: 'set',
      description: 'Contract company name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    billing_frequency: {
      ai: 'billing_frequency',
      grid: 'billing_frequency',
      type: 'set',
      description: 'Contract billing frequency.',
      values: ['monthly', 'quarterly', 'annual', 'other'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    start_date: {
      ai: 'start_date',
      grid: 'start_date',
      type: 'date',
      description: 'Contract start date.',
      sortable: true,
      groupable: false,
    },
    end_date: {
      ai: 'end_date',
      grid: 'end_date',
      type: 'date',
      description: 'Derived contract end date.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    cancellation_deadline: {
      ai: 'cancellation_deadline',
      grid: 'cancellation_deadline',
      type: 'date',
      description: 'Derived contract cancellation deadline.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    duration_months: {
      ai: 'duration_months',
      grid: 'duration_months',
      type: 'number',
      description: 'Contract duration in months.',
      sortable: true,
      groupable: false,
    },
    auto_renewal: {
      ai: 'auto_renewal',
      grid: 'auto_renewal',
      type: 'set',
      description: 'Whether the contract auto-renews.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    notice_period_months: {
      ai: 'notice_period_months',
      grid: 'notice_period_months',
      type: 'number',
      description: 'Notice period in months.',
      sortable: true,
      groupable: false,
    },
    yearly_amount: {
      ai: 'yearly_amount',
      grid: 'yearly_amount_at_signature',
      type: 'number',
      description: 'Yearly amount at signature.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    yearly_amount_at_signature: {
      ai: 'yearly_amount_at_signature',
      grid: 'yearly_amount_at_signature',
      type: 'number',
      description: 'Yearly amount at signature.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
  },
  sortFields: {
    label: 'name',
    status: 'status',
    supplier: 'supplier_name',
    company: 'company_name',
    currency: 'currency',
    billing_frequency: 'billing_frequency',
    start_date: 'start_date',
    duration_months: 'duration_months',
    auto_renewal: 'auto_renewal',
    notice_period_months: 'notice_period_months',
    end_date: 'end_date',
    cancellation_deadline: 'cancellation_deadline',
    yearly_amount: 'yearly_amount_at_signature',
    yearly_amount_at_signature: 'yearly_amount_at_signature',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'contracts',
    alias: 'c',
    groupFields: {
      status: { expression: 'c.status' },
      supplier: {
        expression: 'sup.name',
        joins: [
          `LEFT JOIN suppliers sup ON sup.id = c.supplier_id AND sup.tenant_id = c.tenant_id`,
        ],
      },
      company: {
        expression: 'comp.name',
        joins: [
          `LEFT JOIN companies comp ON comp.id = c.company_id AND comp.tenant_id = c.tenant_id`,
        ],
      },
      currency: { expression: 'c.currency' },
      billing_frequency: { expression: 'c.billing_frequency' },
      auto_renewal: {
        expression: `CASE WHEN c.auto_renewal THEN 'true' ELSE 'false' END`,
      },
    },
    metricFields: {
      end_date: {
        expression: `(c.start_date + COALESCE(c.duration_months, 0) * INTERVAL '1 month' - INTERVAL '1 day')::date`,
        type: 'date',
      },
      cancellation_deadline: {
        expression: `(c.start_date + (COALESCE(c.duration_months, 0) - COALESCE(c.notice_period_months, 0)) * INTERVAL '1 month')::date`,
        type: 'date',
      },
      yearly_amount_at_signature: {
        expression: 'c.yearly_amount_at_signature',
        type: 'number',
      },
    },
  },
};
