import { INCIDENT_SEVERITIES, INCIDENT_STATUSES } from '../../../incidents/incident.entity';
import { AiEntityFilterRegistry } from '../ai-filter.types';

export const incidentsRegistry: AiEntityFilterRegistry = {
  entityType: 'incidents',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Incident lifecycle status.',
      values: [...INCIDENT_STATUSES],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    severity: {
      ai: 'severity',
      grid: 'severity',
      type: 'set',
      description: 'Incident severity.',
      values: [...INCIDENT_SEVERITIES],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    category: {
      ai: 'category',
      grid: 'category',
      type: 'set',
      description: 'Incident category code from IT settings.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    owner: {
      ai: 'owner',
      grid: 'owner_name',
      type: 'set',
      description: 'Incident owner display name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    reporter: {
      ai: 'reporter',
      grid: 'reporter_name',
      type: 'set',
      description: 'Incident reporter display name.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: false,
    },
    asset: {
      ai: 'asset',
      grid: 'linked_assets',
      type: 'text',
      description: 'Linked asset reference or name.',
      discoverable: true,
      sortable: false,
      groupable: false,
      aliases: ['asset_id', 'server', 'linked_asset', 'hostname'],
    },
    application: {
      ai: 'application',
      grid: 'linked_applications',
      type: 'text',
      description: 'Linked application reference or name.',
      discoverable: true,
      sortable: false,
      groupable: false,
      aliases: ['application_id', 'app', 'linked_application'],
    },
    started_at: {
      ai: 'started_at',
      grid: 'started_at',
      type: 'date',
      description: 'When the incident actually began.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    detected_at: {
      ai: 'detected_at',
      grid: 'detected_at',
      type: 'date',
      description: 'When the incident was noticed.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    resolved_at: {
      ai: 'resolved_at',
      grid: 'resolved_at',
      type: 'date',
      description: 'When service was restored.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    closed_at: {
      ai: 'closed_at',
      grid: 'closed_at',
      type: 'date',
      description: 'When the incident record was closed.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    source_ref: {
      ai: 'source_ref',
      grid: 'source_ref',
      type: 'text',
      description: 'External ticket, alert or mail reference.',
      discoverable: true,
      sortable: false,
      groupable: false,
    },
    personal_data_affected: {
      ai: 'personal_data_affected',
      grid: 'personal_data_affected',
      type: 'set',
      description: 'Whether personal data was affected.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: false,
    },
    authority_notification_required: {
      ai: 'authority_notification_required',
      grid: 'authority_notification_required',
      type: 'set',
      description: 'Whether an authority must be notified.',
      values: ['true', 'false'],
      discoverable: true,
      sortable: true,
      groupable: false,
    },
    asset_count: {
      ai: 'asset_count',
      grid: 'asset_count',
      type: 'number',
      description: 'Number of linked assets.',
      sortable: true,
      groupable: false,
    },
    task_count: {
      ai: 'task_count',
      grid: 'task_count',
      type: 'number',
      description: 'Number of follow-up tasks.',
      sortable: true,
      groupable: false,
    },
  },
  sortFields: {
    label: 'title',
    ref: 'item_number',
    severity: 'severity',
    status: 'status',
    detected_at: 'detected_at',
    resolved_at: 'resolved_at',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'detected_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'incidents',
    alias: 'i',
    groupFields: {
      status: { expression: 'i.status' },
      severity: { expression: 'i.severity' },
      category: { expression: 'i.category' },
      owner: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(o.first_name, ' ', o.last_name)), ''), o.email)`,
        joins: [
          `LEFT JOIN users o ON o.id = i.owner_user_id AND o.tenant_id = i.tenant_id`,
        ],
      },
    },
    metricFields: {
      started_at: {
        expression: 'i.started_at',
        type: 'date',
      },
      detected_at: {
        expression: 'i.detected_at',
        type: 'date',
      },
      resolved_at: {
        expression: 'i.resolved_at',
        type: 'date',
      },
      closed_at: {
        expression: 'i.closed_at',
        type: 'date',
      },
    },
  },
};
