import { AiEntityFilterRegistry } from '../ai-filter.types';

export const interfacesRegistry: AiEntityFilterRegistry = {
  entityType: 'interfaces',
  fields: {
    lifecycle: {
      ai: 'lifecycle',
      grid: 'lifecycle',
      type: 'set',
      description: 'Interface lifecycle.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    criticality: {
      ai: 'criticality',
      grid: 'criticality',
      type: 'set',
      description: 'Interface criticality.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    data_category: {
      ai: 'data_category',
      grid: 'data_category',
      type: 'set',
      description: 'Interface data category.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    data_class: {
      ai: 'data_class',
      grid: 'data_class',
      type: 'set',
      description: 'Interface data class.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    integration_route_type: {
      ai: 'integration_route_type',
      grid: 'integration_route_type',
      type: 'set',
      description: 'Interface route type.',
      values: ['direct', 'via_middleware'],
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    source_application: {
      ai: 'source_application',
      grid: 'source_application_name',
      type: 'text',
      description: 'Source application name.',
      sortable: false,
      groupable: true,
    },
    target_application: {
      ai: 'target_application',
      grid: 'target_application_name',
      type: 'text',
      description: 'Target application name.',
      sortable: false,
      groupable: true,
    },
    business_process: {
      ai: 'business_process',
      grid: 'business_process_name',
      type: 'text',
      description: 'Linked business process name.',
      sortable: false,
      groupable: true,
    },
  },
  sortFields: {
    label: 'name',
    interface_id: 'interface_id',
    name: 'name',
    lifecycle: 'lifecycle',
    criticality: 'criticality',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'interfaces',
    alias: 'i',
    groupFields: {
      lifecycle: { expression: 'i.lifecycle' },
      criticality: { expression: 'i.criticality' },
      data_category: { expression: 'i.data_category' },
      data_class: { expression: 'i.data_class' },
      integration_route_type: { expression: 'i.integration_route_type' },
      source_application: {
        expression: 'sa.name',
        joins: ['LEFT JOIN applications sa ON sa.id = i.source_application_id AND sa.tenant_id = i.tenant_id'],
      },
      target_application: {
        expression: 'ta.name',
        joins: ['LEFT JOIN applications ta ON ta.id = i.target_application_id AND ta.tenant_id = i.tenant_id'],
      },
      business_process: {
        expression: 'bp.name',
        joins: ['LEFT JOIN business_processes bp ON bp.id = i.business_process_id AND bp.tenant_id = i.tenant_id'],
      },
    },
  },
};
