import { AiEntityFilterRegistry } from '../ai-filter.types';

export const locationsRegistry: AiEntityFilterRegistry = {
  entityType: 'locations',
  fields: {
    location_reference: {
      ai: 'location_reference',
      grid: 'location_reference',
      type: 'text',
      description: 'System-generated location reference (e.g. LOC-7).',
      discoverable: true,
      sortable: true,
    },
    name: {
      ai: 'name',
      grid: 'name',
      type: 'text',
      description: 'Location name.',
      discoverable: true,
      sortable: true,
    },
    hosting_type: {
      ai: 'hosting_type',
      grid: 'hosting_type',
      type: 'set',
      description: 'Hosting type (e.g. on_prem, cloud).',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    provider: {
      ai: 'provider',
      grid: 'provider',
      type: 'set',
      description: 'Cloud provider.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    country: {
      ai: 'country',
      grid: 'country_iso',
      type: 'set',
      description: 'Country ISO code.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    country_iso: {
      ai: 'country_iso',
      grid: 'country_iso',
      type: 'set',
      description: 'Country ISO code.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    city: {
      ai: 'city',
      grid: 'city',
      type: 'text',
      description: 'City.',
      discoverable: true,
      sortable: true,
      groupable: true,
    },
  },
  sortFields: {
    location_reference: 'location_reference',
    name: 'name',
    hosting_type: 'hosting_type',
    provider: 'provider',
    country: 'country_iso',
    country_iso: 'country_iso',
    city: 'city',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'name',
    direction: 'asc',
  },
  aggregate: {
    baseTable: 'locations',
    alias: 'l',
    groupFields: {
      hosting_type: { expression: 'l.hosting_type' },
      provider: { expression: 'l.provider' },
      country: { expression: 'l.country_iso' },
      country_iso: { expression: 'l.country_iso' },
      city: { expression: 'l.city' },
    },
  },
};
