import { AiEntityFilterRegistry } from '../ai-filter.types';

export const spendItemsRegistry: AiEntityFilterRegistry = {
  entityType: 'spend_items',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Spend item lifecycle status.',
      values: ['enabled', 'disabled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    currency: {
      ai: 'currency',
      grid: 'currency',
      type: 'set',
      description: 'Spend item currency.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    supplier: {
      ai: 'supplier',
      grid: 'supplier_name',
      type: 'set',
      description: 'Supplier name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    paying_company: {
      ai: 'paying_company',
      grid: 'paying_company_name',
      type: 'set',
      description: 'Paying company name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    account: {
      ai: 'account',
      grid: 'account_display',
      type: 'set',
      description: 'Account display value.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    owner_it: {
      ai: 'owner_it',
      grid: 'owner_it_name',
      type: 'set',
      description: 'IT owner display name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    owner_business: {
      ai: 'owner_business',
      grid: 'owner_business_name',
      type: 'set',
      description: 'Business owner display name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    analytics_category: {
      ai: 'analytics_category',
      grid: 'analytics_category_name',
      type: 'set',
      description: 'Analytics category.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    allocation_method: {
      ai: 'allocation_method',
      grid: 'allocation_method_label',
      type: 'set',
      description: 'Allocation method label.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: false,
    },
    contract: {
      ai: 'contract',
      grid: 'contract_name',
      type: 'set',
      description: 'Latest linked contract name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: false,
    },
    project_name: {
      ai: 'project_name',
      grid: 'project_name',
      type: 'text',
      description: 'Linked project name.',
      sortable: true,
      groupable: false,
    },
    project_stream: {
      ai: 'project_stream',
      grid: 'project_stream_name',
      type: 'set',
      description: 'Linked project stream name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    project_category: {
      ai: 'project_category',
      grid: 'project_category_name',
      type: 'set',
      description: 'Linked project category name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    effective_start: {
      ai: 'effective_start',
      grid: 'effective_start',
      type: 'date',
      description: 'Effective start date.',
      sortable: true,
      groupable: false,
    },
    effective_end: {
      ai: 'effective_end',
      grid: 'effective_end',
      type: 'date',
      description: 'Effective end date.',
      sortable: true,
      groupable: false,
    },
    y_budget: {
      ai: 'y_budget',
      grid: 'yBudget',
      type: 'number',
      description: 'Current-year budget total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_review: {
      ai: 'y_review',
      grid: 'yRevision',
      type: 'number',
      description: 'Current-year review total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_actual: {
      ai: 'y_actual',
      grid: 'yFollowUp',
      type: 'number',
      description: 'Current-year actual total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_landing: {
      ai: 'y_landing',
      grid: 'yLanding',
      type: 'number',
      description: 'Current-year landing total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_minus2_budget: {
      ai: 'y_minus2_budget',
      grid: 'yMinus2Budget',
      type: 'number',
      description: 'Budget total for Y-2.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_minus1_budget: {
      ai: 'y_minus1_budget',
      grid: 'yMinus1Budget',
      type: 'number',
      description: 'Budget total for Y-1.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_plus1_budget: {
      ai: 'y_plus1_budget',
      grid: 'yPlus1Budget',
      type: 'number',
      description: 'Next-year budget total.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    y_plus2_budget: {
      ai: 'y_plus2_budget',
      grid: 'yPlus2Budget',
      type: 'number',
      description: 'Budget total for Y+2.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
  },
  sortFields: {
    label: 'product_name',
    status: 'status',
    currency: 'currency',
    supplier: 'supplier_name',
    paying_company: 'paying_company_name',
    account: 'account_display',
    owner_it: 'owner_it_name',
    owner_business: 'owner_business_name',
    analytics_category: 'analytics_category_name',
    allocation_method: 'allocation_method_label',
    contract: 'contract_name',
    project_name: 'project_name',
    project_stream: 'project_stream_name',
    project_category: 'project_category_name',
    effective_start: 'effective_start',
    effective_end: 'effective_end',
    y_minus2_budget: 'yMinus2Budget',
    y_minus1_budget: 'yMinus1Budget',
    y_budget: 'yBudget',
    y_review: 'yRevision',
    y_actual: 'yFollowUp',
    y_landing: 'yLanding',
    y_plus1_budget: 'yPlus1Budget',
    y_plus2_budget: 'yPlus2Budget',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'spend_items',
    alias: 'si',
    groupFields: {
      status: { expression: 'si.status' },
      currency: { expression: 'si.currency' },
      supplier: {
        expression: 'sup.name',
        joins: [
          `LEFT JOIN suppliers sup ON sup.id = si.supplier_id AND sup.tenant_id = si.tenant_id`,
        ],
      },
      paying_company: {
        expression: 'comp.name',
        joins: [
          `LEFT JOIN companies comp ON comp.id = si.paying_company_id AND comp.tenant_id = si.tenant_id`,
        ],
      },
      account: {
        expression: `NULLIF(TRIM(CONCAT_WS(' ', acc.account_number, acc.account_name)), '')`,
        joins: [
          `LEFT JOIN accounts acc ON acc.id = si.account_id AND acc.tenant_id = si.tenant_id`,
        ],
      },
      owner_it: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_it.first_name, ' ', u_it.last_name)), ''), u_it.email)`,
        joins: [
          `LEFT JOIN users u_it ON u_it.id = si.owner_it_id AND u_it.tenant_id = si.tenant_id`,
        ],
      },
      owner_business: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_biz.first_name, ' ', u_biz.last_name)), ''), u_biz.email)`,
        joins: [
          `LEFT JOIN users u_biz ON u_biz.id = si.owner_business_id AND u_biz.tenant_id = si.tenant_id`,
        ],
      },
      analytics_category: {
        expression: 'ac.name',
        joins: [
          `LEFT JOIN analytics_categories ac ON ac.id = si.analytics_category_id AND ac.tenant_id = si.tenant_id`,
        ],
      },
      project_stream: {
        expression: 'pst.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = si.project_id AND pp.tenant_id = si.tenant_id`,
          `LEFT JOIN portfolio_streams pst ON pst.id = pp.stream_id AND pst.tenant_id = si.tenant_id`,
        ],
      },
      project_category: {
        expression: 'pc.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = si.project_id AND pp.tenant_id = si.tenant_id`,
          `LEFT JOIN portfolio_categories pc ON pc.id = pp.category_id AND pc.tenant_id = si.tenant_id`,
        ],
      },
    },
  },
};
