import { AiEntityFilterRegistry } from '../ai-filter.types';

export const tasksRegistry: AiEntityFilterRegistry = {
  entityType: 'tasks',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'Task status.',
      values: ['open', 'in_progress', 'pending', 'in_testing', 'done', 'cancelled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    assignee: {
      ai: 'assignee',
      grid: 'assignee_name',
      type: 'set',
      description: 'Assignee display name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    creator: {
      ai: 'creator',
      grid: 'creator_name',
      type: 'set',
      description: 'Task creator display name.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    priority: {
      ai: 'priority',
      grid: 'priority_level',
      type: 'set',
      description: 'Task priority level.',
      values: ['blocker', 'high', 'normal', 'low', 'optional'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    type: {
      ai: 'type',
      grid: 'task_type_name',
      type: 'set',
      description: 'Task type.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    category: {
      ai: 'category',
      grid: 'category_name',
      type: 'set',
      description: 'Resolved portfolio category.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    stream: {
      ai: 'stream',
      grid: 'stream_name',
      type: 'set',
      description: 'Resolved portfolio stream.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    company: {
      ai: 'company',
      grid: 'company_name',
      type: 'set',
      description: 'Resolved company.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    related: {
      ai: 'related',
      grid: 'related_object_type',
      type: 'set',
      description: 'Related object family.',
      values: ['project', 'spend_item', 'contract', 'capex_item'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    source: {
      ai: 'source',
      grid: 'source_name',
      type: 'set',
      description: 'Resolved source.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    due_date: {
      ai: 'due_date',
      grid: 'due_date',
      type: 'date',
      description: 'Task due date.',
      sortable: true,
      groupable: false,
    },
    labels: {
      ai: 'labels',
      grid: 'labels',
      type: 'text',
      description: 'Task labels.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: false,
    },
    project_name: {
      ai: 'project_name',
      grid: 'project_name',
      type: 'text',
      description: 'Related project name.',
      sortable: false,
      groupable: false,
    },
    project_stream: {
      ai: 'project_stream',
      grid: 'project_stream_name',
      type: 'set',
      description: 'Related project stream name.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
    project_category: {
      ai: 'project_category',
      grid: 'project_category_name',
      type: 'set',
      description: 'Related project category name.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: true,
    },
  },
  sortFields: {
    label: 'title',
    status: 'status',
    assignee: 'assignee_name',
    priority: 'priority_level',
    type: 'task_type_name',
    category: 'category_name',
    stream: 'stream_name',
    company: 'company_name',
    related: 'related_object_type',
    source: 'source_name',
    due_date: 'due_date',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'created_at',
    direction: 'desc',
  },
  aggregate: {
    baseTable: 'tasks',
    alias: 't',
    groupFields: {
      status: { expression: 't.status' },
      assignee: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u.first_name, ' ', u.last_name)), ''), u.email)`,
        joins: [
          `LEFT JOIN users u ON u.id = t.assignee_user_id AND u.tenant_id = t.tenant_id`,
        ],
      },
      creator: {
        expression: `COALESCE(NULLIF(TRIM(CONCAT(u_creator.first_name, ' ', u_creator.last_name)), ''), u_creator.email)`,
        joins: [
          `LEFT JOIN users u_creator ON u_creator.id = t.creator_id AND u_creator.tenant_id = t.tenant_id`,
        ],
      },
      priority: { expression: 't.priority_level' },
      type: {
        expression: 'tt.name',
        joins: [
          `LEFT JOIN portfolio_task_types tt ON tt.id = t.task_type_id AND tt.tenant_id = t.tenant_id`,
        ],
      },
      category: {
        expression: 'pc.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = t.related_object_id AND t.related_object_type = 'project' AND pp.tenant_id = t.tenant_id`,
          `LEFT JOIN portfolio_categories pc ON pc.id = COALESCE(t.category_id, pp.category_id) AND pc.tenant_id = t.tenant_id`,
        ],
      },
      stream: {
        expression: 'pst.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = t.related_object_id AND t.related_object_type = 'project' AND pp.tenant_id = t.tenant_id`,
          `LEFT JOIN portfolio_streams pst ON pst.id = COALESCE(t.stream_id, pp.stream_id) AND pst.tenant_id = t.tenant_id`,
        ],
      },
      company: {
        expression: 'comp.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = t.related_object_id AND t.related_object_type = 'project' AND pp.tenant_id = t.tenant_id`,
          `LEFT JOIN companies comp ON comp.id = COALESCE(t.company_id, pp.company_id) AND comp.tenant_id = t.tenant_id`,
        ],
      },
      related: { expression: 't.related_object_type' },
      source: {
        expression: 'ps.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = t.related_object_id AND t.related_object_type = 'project' AND pp.tenant_id = t.tenant_id`,
          `LEFT JOIN portfolio_sources ps ON ps.id = COALESCE(t.source_id, pp.source_id) AND ps.tenant_id = t.tenant_id`,
        ],
      },
      project_stream: {
        expression: 'project_pst.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = t.related_object_id AND t.related_object_type = 'project' AND pp.tenant_id = t.tenant_id`,
          `LEFT JOIN portfolio_streams project_pst ON project_pst.id = pp.stream_id AND project_pst.tenant_id = t.tenant_id`,
        ],
      },
      project_category: {
        expression: 'project_pc.name',
        joins: [
          `LEFT JOIN portfolio_projects pp ON pp.id = t.related_object_id AND t.related_object_type = 'project' AND pp.tenant_id = t.tenant_id`,
          `LEFT JOIN portfolio_categories project_pc ON project_pc.id = pp.category_id AND project_pc.tenant_id = t.tenant_id`,
        ],
      },
    },
  },
};
