import { AiEntityFilterRegistry } from '../ai-filter.types';

const contributorProfileExpression = `CASE WHEN tmc.id IS NULL THEN 'not_configured' ELSE 'configured' END`;

export const usersRegistry: AiEntityFilterRegistry = {
  entityType: 'users',
  fields: {
    status: {
      ai: 'status',
      grid: 'status',
      type: 'set',
      description: 'User lifecycle status.',
      values: ['enabled', 'disabled'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    email: {
      ai: 'email',
      grid: 'email',
      type: 'text',
      description: 'User email address.',
      sortable: true,
      groupable: false,
    },
    first_name: {
      ai: 'first_name',
      grid: 'first_name',
      type: 'text',
      description: 'User first name.',
      sortable: true,
      groupable: false,
    },
    last_name: {
      ai: 'last_name',
      grid: 'last_name',
      type: 'text',
      description: 'User last name.',
      sortable: true,
      groupable: false,
    },
    job_title: {
      ai: 'job_title',
      grid: 'job_title',
      type: 'text',
      description: 'User job title.',
      sortable: true,
      groupable: false,
    },
    company: {
      ai: 'company',
      grid: 'company_name',
      type: 'set',
      description: 'User company name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    department: {
      ai: 'department',
      grid: 'department_name',
      type: 'set',
      description: 'User department name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    primary_role: {
      ai: 'primary_role',
      grid: 'primary_role_name',
      type: 'set',
      description: 'User primary role name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    locale: {
      ai: 'locale',
      grid: 'locale',
      type: 'set',
      description: 'User locale.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    team: {
      ai: 'team',
      grid: 'team_name',
      type: 'set',
      description: 'Contributor team name.',
      dynamic: true,
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    contributor_profile: {
      ai: 'contributor_profile',
      grid: 'contributor_profile',
      type: 'set',
      description: 'Whether the user has a contributor profile.',
      values: ['configured', 'not_configured'],
      discoverable: true,
      sortable: true,
      groupable: true,
    },
    project_availability: {
      ai: 'project_availability',
      grid: 'project_availability',
      type: 'number',
      description: 'Contributor project availability in days per week.',
      sortable: true,
      groupable: false,
      aggregable: true,
    },
    areas_of_expertise: {
      ai: 'areas_of_expertise',
      grid: 'areas_of_expertise',
      type: 'text',
      description: 'Contributor areas of expertise.',
      dynamic: true,
      discoverable: true,
      sortable: false,
      groupable: false,
    },
  },
  sortFields: {
    label: 'display_name',
    email: 'email',
    first_name: 'first_name',
    last_name: 'last_name',
    status: 'status',
    job_title: 'job_title',
    company: 'company_name',
    department: 'department_name',
    primary_role: 'primary_role_name',
    locale: 'locale',
    team: 'team_name',
    contributor_profile: 'contributor_profile',
    project_availability: 'project_availability',
    created_at: 'created_at',
    updated_at: 'updated_at',
  },
  defaultSort: {
    field: 'last_name',
    direction: 'asc',
  },
  aggregate: {
    baseTable: 'users',
    alias: 'u',
    groupFields: {
      status: { expression: 'u.status' },
      company: {
        expression: 'c.name',
        joins: [
          `LEFT JOIN companies c ON c.id = u.company_id AND c.tenant_id = u.tenant_id`,
        ],
      },
      department: {
        expression: 'd.name',
        joins: [
          `LEFT JOIN departments d ON d.id = u.department_id AND d.tenant_id = u.tenant_id`,
        ],
      },
      primary_role: {
        expression: 'r.role_name',
        joins: [
          `LEFT JOIN roles r ON r.id = u.role_id AND r.tenant_id = u.tenant_id`,
        ],
      },
      locale: { expression: 'u.locale' },
      team: {
        expression: 'pt.name',
        joins: [
          `LEFT JOIN portfolio_team_member_configs tmc ON tmc.user_id = u.id AND tmc.tenant_id = u.tenant_id`,
          `LEFT JOIN portfolio_teams pt ON pt.id = tmc.team_id AND pt.tenant_id = u.tenant_id`,
        ],
      },
      contributor_profile: {
        expression: contributorProfileExpression,
        joins: [
          `LEFT JOIN portfolio_team_member_configs tmc ON tmc.user_id = u.id AND tmc.tenant_id = u.tenant_id`,
        ],
      },
    },
    metricFields: {
      project_availability: {
        expression: 'tmc.project_availability',
        type: 'number',
        joins: [
          `LEFT JOIN portfolio_team_member_configs tmc ON tmc.user_id = u.id AND tmc.tenant_id = u.tenant_id`,
        ],
      },
    },
  },
};
