import type { TrialContent } from './types';

const content: TrialContent = {
  start: {
    title: 'Kostenlose Testversion starten',
    description: 'Erstellen Sie Ihren KANAP-Workspace. 14 Tage, keine Kreditkarte, kostenlose 60-min Aktivierungssitzung.',
    eyebrow: 'Kostenlose Testversion',
    heading: 'Starten Sie Ihre kostenlose Testversion.',
    lead: 'Workspace in einer Minute erstellen. Sie erhalten einen Link per E-Mail, setzen Ihr Passwort und sind drin. 14 Tage, alle Funktionen, keine Kreditkarte.',
    benefits: [
      'Alle Funktionen 14 Tage freigeschaltet',
      'Kostenlose 60-min Aktivierungssitzung',
      'Keine Kreditkarte, Sie entscheiden am Ende',
      'Self-Hosting-Alternative jederzeit verfügbar',
    ],
    form: {
      orgLabel: 'Name der Organisation',
      orgHelp: 'Der Anzeigename, den Ihr Team oben in der App sieht.',
      countryLabel: 'Land',
      countryHelp: 'Wird für Ihre Standardwährung und Standardfirma verwendet.',
      slugLabel: 'Workspace-URL',
      slugHelp: 'Kleinbuchstaben, Ziffern und Bindestriche.',
      slugDomain: '.kanap.net',
      emailLabel: 'Admin-E-Mail',
      emailHelp: 'Der Aktivierungslink wird hierhin geschickt. Dies wird der erste Admin-Account.',
      submitLabel: 'Aktivierungslink senden',
      submitting: 'Wird gesendet …',
      errorGeneric: 'Etwas ist schiefgelaufen. Bitte erneut versuchen oder uns kontaktieren.',
      errorRequired: 'Dieses Feld ist erforderlich.',
      errorEmail: 'Geben Sie eine gültige E-Mail-Adresse ein.',
      errorSlug: 'Nur Kleinbuchstaben, Ziffern und Bindestriche.',
      captchaLabel: 'Sicherheitsprüfung',
      privacyNote: 'Ihre E-Mail wird nur für den Aktivierungslink und erste Nutzungshinweise verwendet. Kein Newsletter.',
    },
    countryOptions: [
      { value: 'DE', label: 'Deutschland' },
      { value: 'AT', label: 'Österreich' },
      { value: 'CH', label: 'Schweiz' },
      { value: 'FR', label: 'Frankreich' },
      { value: 'ES', label: 'Spanien' },
      { value: 'IT', label: 'Italien' },
      { value: 'BE', label: 'Belgien' },
      { value: 'NL', label: 'Niederlande' },
      { value: 'LU', label: 'Luxemburg' },
      { value: 'GB', label: 'Vereinigtes Königreich' },
      { value: 'IE', label: 'Irland' },
      { value: 'PT', label: 'Portugal' },
      { value: 'US', label: 'Vereinigte Staaten' },
      { value: 'CA', label: 'Kanada' },
      { value: 'OTHER', label: 'Andere' },
    ],
  },

  checkEmail: {
    title: 'E-Mail prüfen',
    description: 'Wir haben Ihnen den Aktivierungslink geschickt. Klicken Sie ihn an, um Ihren Workspace fertigzustellen.',
    eyebrow: 'Fast geschafft',
    heading: 'Prüfen Sie Ihre E-Mail.',
    lead: 'Wir haben einen Aktivierungslink an die angegebene Adresse geschickt. Klicken Sie ihn an, um die Workspace-Erstellung abzuschließen.',
    whatNext: 'Wie es weitergeht',
    steps: [
      'Posteingang öffnen, Betreff „Aktivieren Sie Ihren KANAP-Workspace".',
      'Auf den Link klicken. Wir erstellen Ihren Workspace in Sekunden.',
      'Admin-Passwort setzen. Einloggen, Team einladen, loslegen.',
    ],
    noEmailTitle: 'E-Mail nicht erhalten?',
    noEmailBody: 'Kann eine Minute dauern. Spam-Ordner prüfen. Falls weiterhin keine E-Mail kommt, Formular neu starten oder uns kontaktieren.',
    resendLabel: 'Formular neu starten',
    restartLabel: 'Formular neu starten',
  },

  activate: {
    title: 'Workspace wird aktiviert',
    description: 'Bitte warten, während wir Ihren Workspace vorbereiten.',
    eyebrow: 'Workspace-Aktivierung',
    heading: 'Bitte warten, wir bereiten Ihren Workspace vor.',
    lead: 'Wir prüfen Ihren Aktivierungslink und stellen Ihren Workspace bereit. Das dauert ein paar Sekunden. Danach werden Sie zum Passwort-Setzen weitergeleitet.',
    progressIdle: 'Wird gestartet …',
    progressValidating: 'Link wird geprüft …',
    progressCreating: 'Workspace wird erstellt …',
    progressRedirecting: 'Weiterleitung zum Passwort-Setzen …',
    successPrefix: 'Workspace bereit!',
    redirectNote: 'Startet die Weiterleitung nicht, klicken Sie den Button unten.',
  },

  expired: {
    title: 'Aktivierungslink abgelaufen',
    description: 'Dieser Aktivierungslink ist nicht mehr gültig. Starten Sie das Formular für einen neuen.',
    eyebrow: 'Link abgelaufen',
    heading: 'Dieser Link ist abgelaufen.',
    lead: 'Aktivierungslinks sind 48 Stunden gültig. Starten Sie das Formular neu, wir senden Ihnen einen frischen.',
    body: 'Haben Sie das Formular mehrmals ausgeführt, ist nur der letzte Link gültig. Kommen Sie wiederholt hier an, schreiben Sie uns, wir lösen es manuell.',
    restartLabel: 'Formular neu starten',
    contactLabel: 'Support kontaktieren',
  },

  failed: {
    title: 'Aktivierung fehlgeschlagen',
    description: 'Bei der Aktivierung ist etwas schiefgelaufen. Kontaktieren Sie uns, wir lösen es.',
    eyebrow: 'Aktivierung fehlgeschlagen',
    heading: 'Etwas ist schiefgelaufen.',
    lead: 'Wir konnten Ihren Workspace nicht aktivieren. Häufigste Ursache: Link bereits benutzt. Sonst untersuchen wir bereits.',
    body: 'Bleibt das so, kontaktieren Sie den Support. Geben Sie die verwendete E-Mail und möglichst die Uhrzeit des Link-Klicks an.',
    restartLabel: 'Formular neu starten',
    contactLabel: 'Support kontaktieren',
  },
};

export default content;
