import type { TrialContent } from './types';

const content: TrialContent = {
  start: {
    title: 'Start your free trial',
    description: 'Create your KANAP workspace. 14-day trial, no credit card, free 60-minute activation session.',
    eyebrow: 'Free trial',
    heading: 'Start your free trial.',
    lead: 'Create your workspace in a minute. You\'ll get a link by email, set your password, and you\'re in. 14 days, all features, no credit card.',
    benefits: [
      'All features unlocked for 14 days',
      'Free 60-minute activation session included',
      'No credit card, decide at the end',
      'Self-hosting alternative available at any time',
    ],
    form: {
      orgLabel: 'Organisation name',
      orgHelp: 'The display name your team will see at the top of the app.',
      countryLabel: 'Country',
      countryHelp: 'Used to set your default currency and default company.',
      slugLabel: 'Workspace URL',
      slugHelp: 'Lowercase letters, numbers, and hyphens.',
      slugDomain: '.kanap.net',
      emailLabel: 'Admin email',
      emailHelp: 'The activation link will be sent here. This becomes the first admin user.',
      submitLabel: 'Send activation link',
      submitting: 'Sending…',
      errorGeneric: 'Something went wrong. Please try again or contact us.',
      errorRequired: 'This field is required.',
      errorEmail: 'Enter a valid email address.',
      errorSlug: 'Only lowercase letters, numbers and hyphens.',
      captchaLabel: 'Security check',
      privacyNote: 'We use the email only to send your activation link and first-use guidance. No newsletter.',
    },
    countryOptions: [
      { value: 'FR', label: 'France' },
      { value: 'DE', label: 'Germany' },
      { value: 'ES', label: 'Spain' },
      { value: 'IT', label: 'Italy' },
      { value: 'BE', label: 'Belgium' },
      { value: 'NL', label: 'Netherlands' },
      { value: 'LU', label: 'Luxembourg' },
      { value: 'CH', label: 'Switzerland' },
      { value: 'AT', label: 'Austria' },
      { value: 'GB', label: 'United Kingdom' },
      { value: 'IE', label: 'Ireland' },
      { value: 'PT', label: 'Portugal' },
      { value: 'US', label: 'United States' },
      { value: 'CA', label: 'Canada' },
      { value: 'OTHER', label: 'Other' },
    ],
  },

  checkEmail: {
    title: 'Check your email',
    description: 'We\'ve sent the activation link. Click it to finish creating your workspace.',
    eyebrow: 'Almost there',
    heading: 'Check your email.',
    lead: 'We\'ve sent an activation link to the address you provided. Click it to finish creating your workspace.',
    whatNext: 'What happens next',
    steps: [
      'Open your inbox, subject line "Activate your KANAP workspace".',
      'Click the link. We\'ll create your workspace in a few seconds.',
      'Set your admin password. Log in, invite your team, start.',
    ],
    noEmailTitle: 'Didn\'t receive the email?',
    noEmailBody: 'It can take a minute. Check your spam folder. If it still doesn\'t arrive, restart the form or contact us.',
    resendLabel: 'Restart the form',
    restartLabel: 'Restart the form',
  },

  activate: {
    title: 'Activating your workspace',
    description: 'Hold on while we prepare your workspace.',
    eyebrow: 'Workspace activation',
    heading: 'Hold on while we prepare your workspace.',
    lead: 'We\'re validating your activation link and provisioning your workspace. This takes a few seconds. You\'ll be redirected to set your password once it\'s ready.',
    progressIdle: 'Starting…',
    progressValidating: 'Validating your link…',
    progressCreating: 'Creating your workspace…',
    progressRedirecting: 'Redirecting you to set your password…',
    successPrefix: 'Workspace ready!',
    redirectNote: 'If the redirection doesn\'t start automatically, click the button below.',
  },

  expired: {
    title: 'Activation link expired',
    description: 'This activation link is no longer valid. Restart the form to get a new one.',
    eyebrow: 'Link expired',
    heading: 'This link has expired.',
    lead: 'Activation links are valid for 48 hours. Restart the form and we\'ll send you a fresh one.',
    body: 'If you ran the form multiple times, only the latest link is valid. If you keep hitting this page, write to us and we\'ll sort it out manually.',
    restartLabel: 'Restart the form',
    contactLabel: 'Contact support',
  },

  failed: {
    title: 'Activation failed',
    description: 'Something went wrong during activation. Contact us and we\'ll resolve it.',
    eyebrow: 'Activation failed',
    heading: 'Something went wrong.',
    lead: 'We couldn\'t activate your workspace. The most common cause is a link that\'s been used already. Otherwise, we\'re already investigating.',
    body: 'If this persists, please contact support. Include the email address you used and, if possible, the time you clicked the link.',
    restartLabel: 'Restart the form',
    contactLabel: 'Contact support',
  },
};

export default content;
