import type { TrialContent } from './types';

const content: TrialContent = {
  start: {
    title: 'Empezar la prueba gratuita',
    description: 'Crea tu workspace KANAP. Prueba de 14 días, sin tarjeta, sesión de activación de 60 min gratuita.',
    eyebrow: 'Prueba gratuita',
    heading: 'Empieza tu prueba gratuita.',
    lead: 'Crea tu workspace en un minuto. Recibirás un enlace por email, define tu contraseña y listo. 14 días, todas las funcionalidades, sin tarjeta.',
    benefits: [
      'Todas las funcionalidades activas durante 14 días',
      'Sesión de activación de 60 min gratuita',
      'Sin tarjeta, decides al final',
      'Alternativa de autoalojamiento disponible en cualquier momento',
    ],
    form: {
      orgLabel: 'Nombre de la organización',
      orgHelp: 'El nombre que verá tu equipo en la parte superior de la aplicación.',
      countryLabel: 'País',
      countryHelp: 'Se usa para definir tu moneda y empresa por defecto.',
      slugLabel: 'URL del workspace',
      slugHelp: 'Letras minúsculas, números y guiones.',
      slugDomain: '.kanap.net',
      emailLabel: 'Email de administrador',
      emailHelp: 'El enlace de activación se enviará aquí. Esta será la primera cuenta de administrador.',
      submitLabel: 'Enviar enlace de activación',
      submitting: 'Enviando…',
      errorGeneric: 'Algo ha fallado. Inténtalo de nuevo o contáctanos.',
      errorRequired: 'Este campo es obligatorio.',
      errorEmail: 'Introduce una dirección de email válida.',
      errorSlug: 'Solo letras minúsculas, números y guiones.',
      captchaLabel: 'Comprobación de seguridad',
      privacyNote: 'Tu email solo se usa para enviarte el enlace de activación y la guía inicial. Sin newsletter.',
    },
    countryOptions: [
      { value: 'ES', label: 'España' },
      { value: 'PT', label: 'Portugal' },
      { value: 'FR', label: 'Francia' },
      { value: 'DE', label: 'Alemania' },
      { value: 'IT', label: 'Italia' },
      { value: 'BE', label: 'Bélgica' },
      { value: 'NL', label: 'Países Bajos' },
      { value: 'LU', label: 'Luxemburgo' },
      { value: 'CH', label: 'Suiza' },
      { value: 'AT', label: 'Austria' },
      { value: 'GB', label: 'Reino Unido' },
      { value: 'IE', label: 'Irlanda' },
      { value: 'US', label: 'Estados Unidos' },
      { value: 'CA', label: 'Canadá' },
      { value: 'OTHER', label: 'Otro' },
    ],
  },

  checkEmail: {
    title: 'Revisa tu email',
    description: 'Hemos enviado el enlace de activación. Haz clic para terminar de crear tu workspace.',
    eyebrow: 'Casi está',
    heading: 'Revisa tu email.',
    lead: 'Hemos enviado un enlace de activación a la dirección proporcionada. Haz clic para terminar de crear tu workspace.',
    whatNext: 'Qué viene ahora',
    steps: [
      'Abre tu bandeja, asunto «Activa tu workspace KANAP».',
      'Haz clic en el enlace. Creamos tu workspace en segundos.',
      'Define tu contraseña admin. Inicia sesión, invita al equipo y comienza.',
    ],
    noEmailTitle: '¿No has recibido el email?',
    noEmailBody: 'Puede tardar un minuto. Revisa la carpeta de spam. Si no llega, reinicia el formulario o contáctanos.',
    resendLabel: 'Reiniciar el formulario',
    restartLabel: 'Reiniciar el formulario',
  },

  activate: {
    title: 'Activando tu workspace',
    description: 'Espera mientras preparamos tu workspace.',
    eyebrow: 'Activación del workspace',
    heading: 'Espera mientras preparamos tu workspace.',
    lead: 'Estamos validando tu enlace y aprovisionando tu workspace. Tarda unos segundos. Te redirigiremos para definir tu contraseña cuando esté listo.',
    progressIdle: 'Iniciando…',
    progressValidating: 'Validando el enlace…',
    progressCreating: 'Creando el workspace…',
    progressRedirecting: 'Redirigiendo para definir tu contraseña…',
    successPrefix: '¡Workspace listo!',
    redirectNote: 'Si la redirección no se inicia automáticamente, haz clic en el botón de abajo.',
  },

  expired: {
    title: 'Enlace de activación caducado',
    description: 'Este enlace de activación ya no es válido. Reinicia el formulario para recibir uno nuevo.',
    eyebrow: 'Enlace caducado',
    heading: 'Este enlace ha caducado.',
    lead: 'Los enlaces de activación son válidos 48 horas. Reinicia el formulario y te enviaremos uno nuevo.',
    body: 'Si rellenaste el formulario varias veces, solo el último enlace es válido. Si sigues aterrizando aquí, escríbenos y lo resolveremos manualmente.',
    restartLabel: 'Reiniciar el formulario',
    contactLabel: 'Contactar con soporte',
  },

  failed: {
    title: 'Activación fallida',
    description: 'Algo ha fallado durante la activación. Contáctanos y lo resolveremos.',
    eyebrow: 'Activación fallida',
    heading: 'Algo ha fallado.',
    lead: 'No hemos podido activar tu workspace. La causa más común es un enlace ya usado. Si no, ya estamos investigando.',
    body: 'Si persiste, contacta con soporte. Indica el email usado y, si es posible, la hora del clic.',
    restartLabel: 'Reiniciar el formulario',
    contactLabel: 'Contactar con soporte',
  },
};

export default content;
