import type { TrialContent } from './types';

const content: TrialContent = {
  start: {
    title: 'Commencer votre essai gratuit',
    description: 'Créez votre workspace KANAP. Essai 14 jours, sans carte bancaire, session d\'activation 60 min offerte.',
    eyebrow: 'Essai gratuit',
    heading: 'Commencez votre essai gratuit.',
    lead: 'Créez votre workspace en une minute. Vous recevrez un lien par email, définissez votre mot de passe, et c\'est parti. 14 jours, toutes les fonctionnalités, sans carte.',
    benefits: [
      'Toutes les fonctionnalités déverrouillées pendant 14 jours',
      'Session d\'activation de 60 min offerte',
      'Sans carte, vous décidez à la fin',
      'Alternative d\'auto-hébergement possible à tout moment',
    ],
    form: {
      orgLabel: 'Nom de l\'organisation',
      orgHelp: 'Le nom affiché que votre équipe verra en haut de l\'application.',
      countryLabel: 'Pays',
      countryHelp: 'Utilisé pour définir votre devise par défaut et la société par défaut.',
      slugLabel: 'URL du workspace',
      slugHelp: 'Lettres minuscules, chiffres et traits d\'union.',
      slugDomain: '.kanap.net',
      emailLabel: 'Email admin',
      emailHelp: 'Le lien d\'activation sera envoyé à cette adresse. Ce sera le premier compte administrateur.',
      submitLabel: 'Envoyer le lien d\'activation',
      submitting: 'Envoi…',
      errorGeneric: 'Une erreur est survenue. Réessayez ou contactez-nous.',
      errorRequired: 'Ce champ est requis.',
      errorEmail: 'Entrez une adresse email valide.',
      errorSlug: 'Uniquement lettres minuscules, chiffres et traits d\'union.',
      captchaLabel: 'Vérification de sécurité',
      privacyNote: 'Votre email ne sert qu\'à vous envoyer le lien d\'activation et les premiers conseils d\'usage. Aucune newsletter.',
    },
    countryOptions: [
      { value: 'FR', label: 'France' },
      { value: 'DE', label: 'Allemagne' },
      { value: 'ES', label: 'Espagne' },
      { value: 'IT', label: 'Italie' },
      { value: 'BE', label: 'Belgique' },
      { value: 'NL', label: 'Pays-Bas' },
      { value: 'LU', label: 'Luxembourg' },
      { value: 'CH', label: 'Suisse' },
      { value: 'AT', label: 'Autriche' },
      { value: 'GB', label: 'Royaume-Uni' },
      { value: 'IE', label: 'Irlande' },
      { value: 'PT', label: 'Portugal' },
      { value: 'US', label: 'États-Unis' },
      { value: 'CA', label: 'Canada' },
      { value: 'OTHER', label: 'Autre' },
    ],
  },

  checkEmail: {
    title: 'Vérifiez votre email',
    description: 'Nous avons envoyé le lien d\'activation. Cliquez dessus pour finaliser votre workspace.',
    eyebrow: 'Presque fini',
    heading: 'Vérifiez votre email.',
    lead: 'Nous avons envoyé un lien d\'activation à l\'adresse fournie. Cliquez dessus pour finaliser la création de votre workspace.',
    whatNext: 'La suite',
    steps: [
      'Ouvrez votre boîte mail, objet « Activer votre workspace KANAP ».',
      'Cliquez sur le lien. Nous créons votre workspace en quelques secondes.',
      'Définissez votre mot de passe admin. Connectez-vous, invitez votre équipe, c\'est parti.',
    ],
    noEmailTitle: 'Vous n\'avez pas reçu l\'email ?',
    noEmailBody: 'Il peut falloir une minute. Vérifiez votre dossier spam. Sinon, relancez le formulaire ou contactez-nous.',
    resendLabel: 'Recommencer le formulaire',
    restartLabel: 'Recommencer le formulaire',
  },

  activate: {
    title: 'Activation de votre workspace',
    description: 'Patientez pendant que nous préparons votre workspace.',
    eyebrow: 'Activation du workspace',
    heading: 'Patientez pendant que nous préparons votre workspace.',
    lead: 'Nous validons votre lien d\'activation et provisionnons votre workspace. Cela prend quelques secondes. Vous serez redirigé pour définir votre mot de passe une fois prêt.',
    progressIdle: 'Démarrage…',
    progressValidating: 'Validation du lien…',
    progressCreating: 'Création du workspace…',
    progressRedirecting: 'Redirection pour définir votre mot de passe…',
    successPrefix: 'Workspace prêt !',
    redirectNote: 'Si la redirection ne démarre pas automatiquement, cliquez sur le bouton ci-dessous.',
  },

  expired: {
    title: 'Lien d\'activation expiré',
    description: 'Ce lien d\'activation n\'est plus valide. Relancez le formulaire pour en recevoir un nouveau.',
    eyebrow: 'Lien expiré',
    heading: 'Ce lien a expiré.',
    lead: 'Les liens d\'activation sont valables 48 heures. Relancez le formulaire et nous vous en enverrons un nouveau.',
    body: 'Si vous avez rempli le formulaire plusieurs fois, seul le dernier lien est valide. Si vous continuez à atterrir ici, écrivez-nous, nous réglerons cela manuellement.',
    restartLabel: 'Recommencer le formulaire',
    contactLabel: 'Contacter le support',
  },

  failed: {
    title: 'Activation échouée',
    description: 'Une erreur est survenue pendant l\'activation. Contactez-nous, nous allons la résoudre.',
    eyebrow: 'Activation échouée',
    heading: 'Une erreur est survenue.',
    lead: 'Nous n\'avons pas pu activer votre workspace. La cause la plus fréquente est un lien déjà utilisé. Sinon, nous enquêtons déjà.',
    body: 'Si cela persiste, contactez le support. Indiquez l\'adresse email utilisée et, si possible, l\'heure du clic sur le lien.',
    restartLabel: 'Recommencer le formulaire',
    contactLabel: 'Contacter le support',
  },
};

export default content;
