import { CsvImportService } from '../../common/csv/csv-import.service';
import { CsvExportService } from '../../common/csv/csv-export.service';
import { CsvResolverService } from '../../common/csv/csv-resolver.service';
import { CsvJsonValidators } from '../../common/csv/csv-json-validators';
import { ApplicationsCsvService } from '../applications-csv.service';
import { ApplicationClassificationV11853480000000 } from '../../migrations/1853480000000-application-classification-v1';
import 'reflect-metadata';
import * as assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import dataSource from '../../data-source';
import { Application } from '../application.entity';
import { Tenant } from '../../tenants/tenant.entity';
import { Location } from '../../locations/location.entity';
import { AuditLog } from '../../audit/audit.entity';
import { AuditService } from '../../audit/audit.service';
import { ItOpsSettingsService } from '../../it-ops-settings/it-ops-settings.service';
import { ApplicationsCrudService } from '../services/applications-crud.service';
import { ApplicationsListService } from '../services/applications-list.service';
import { catalogToMetadata, DEFAULT_CLASSIFICATION_CATALOG } from '../../it-ops-settings/classification-catalog';
import { applicationCsvConfig } from '../application-csv.config';
import { classificationSqlExpressions } from '../../it-ops-settings/classification-sql';

async function main() {
  if (!process.env.DATABASE_URL?.endsWith('/kanap_classification_v1_test')) throw new Error('Only isolated kanap_classification_v1_test is allowed');
  await dataSource.initialize();
  const runner = dataSource.createQueryRunner(); await runner.connect(); await runner.startTransaction();
  const manager = runner.manager;
  const audit = new AuditService(manager.getRepository(AuditLog));
  const settings = new ItOpsSettingsService(manager.getRepository(Tenant), manager.getRepository(Location), audit);
  const crud = new ApplicationsCrudService(manager.getRepository(Application), audit, null as any, settings, null as any, null as any);
  const list = new ApplicationsListService(manager.getRepository(Application));
  const tenantA = randomUUID(), tenantB = randomUUID(), userId = randomUUID();
  try {
    // Exercise the additive migration against populated historical tables as well
    // as the complete fresh database migrated by the CLI.
    await manager.query('CREATE SCHEMA classification_migration_fixture');
    await manager.query('SET LOCAL search_path TO classification_migration_fixture, public');
    await manager.query(`CREATE TABLE tenants(id uuid PRIMARY KEY,metadata jsonb);
      CREATE TABLE applications(id uuid PRIMARY KEY,tenant_id uuid,criticality text NOT NULL DEFAULT 'medium',data_class text,last_dr_test date,contains_pii boolean);
      CREATE TABLE interfaces(tenant_id uuid,criticality text NOT NULL DEFAULT 'medium',data_class text NOT NULL DEFAULT 'internal');
      CREATE TABLE connections(tenant_id uuid,criticality text NOT NULL DEFAULT 'medium',data_class text NOT NULL DEFAULT 'internal');
      CREATE TABLE application_links(id uuid,application_id uuid,tenant_id uuid,url text);
      CREATE TABLE application_data_residency(application_id uuid,tenant_id uuid,country_iso text)`);
    await manager.query(`INSERT INTO tenants VALUES ($1,$2)`,[tenantA,{it_ops:{data_classes:[{code:'private_z',label:'Private'},{code:'public_a',label:'Public'}]}}]);
    await manager.query(`INSERT INTO applications VALUES ($1,$2,'medium','private_z','2026-01-01',false)`,[randomUUID(),tenantA]);
    await new ApplicationClassificationV11853480000000().up(runner);
    const migrated=await manager.query('SELECT * FROM applications');
    assert.equal(migrated[0].criticality,'medium'); assert.equal(migrated[0].legacy_criticality,'medium'); assert.equal(migrated[0].business_mtd_minutes,null); assert.equal(migrated[0].classification_review,null); assert.equal(migrated[0].business_criticality_origin,'legacy'); assert.equal(migrated[0].data_class,'private_z'); assert.equal(migrated[0].contains_pii,false);
    const migratedTenant=await manager.query('SELECT metadata FROM tenants'); assert.deepEqual(migratedTenant[0].metadata.it_ops.data_classes.map((x:any)=>[x.code,x.rank]),[['private_z',1],['public_a',2]]);
    await assert.rejects(()=>new ApplicationClassificationV11853480000000().down(),/non-destructive/);
    await manager.query('SET LOCAL search_path TO public');
    const fixtureCatalog=structuredClone(DEFAULT_CLASSIFICATION_CATALOG); fixtureCatalog.businessMtdPresets.push(30);
    for (const id of [tenantA,tenantB]) await manager.query(`INSERT INTO tenants(id,slug,name,metadata) VALUES ($1,$2,'Classification test',$3)`,[id,`classification-${id}`,{it_ops:catalogToMetadata(fixtureCatalog)}]);
    await manager.query(`SELECT set_config('app.current_tenant',$1,true)`,[tenantA]);
    const roleId = randomUUID();
    await manager.query(`INSERT INTO roles(id,tenant_id,role_name,is_system) VALUES ($1,$2,'Classification reviewer',false)`,[roleId,tenantA]);
    await manager.query(`INSERT INTO users(id,tenant_id,email,first_name,role_id) VALUES ($1,$2,$3,'Reviewer',$4)`,[userId,tenantA,`${userId}@test.invalid`,roleId]);
    const app = await crud.create({name:'Atlas classification'},userId,{manager});
    assert.equal(app.criticality,null); assert.equal(app.data_class,null); assert.equal(app.classification_review,null);
    await assert.rejects(()=>crud.update(app.id,{criticality:'high'},userId,{manager}),/business_mtd_minutes/);
    let updated:any = await crud.update(app.id,{business_mtd_minutes:1440,cyber_criticality:'critical',data_class:'restricted',recovery_wave:'vital',rpo_minutes:0,classification_justification:'Reference production service'},userId,{manager});
    assert.equal(updated.criticality,'high'); assert.equal(updated.rpo_minutes,0);
    const revision = updated.classification_revision;
    updated = await crud.reviewClassification(app.id,revision,userId,{manager});
    assert.equal(updated.classification_review_state,'reviewed');
    updated = await crud.update(app.id,{name:'Atlas renamed'},userId,{manager}); assert.equal(updated.classification_review_state,'reviewed');
    await assert.rejects(()=>crud.reviewClassification(app.id,revision-1,userId,{manager}),/changed/);
    let catalog = await settings.getClassificationCatalog(tenantA,{manager});
    const levels = structuredClone(catalog.businessCriticalityLevels); levels[0].maxMtdMinutes=1500; levels[1].maxMtdMinutes=2000;
    const patch={businessCriticalityLevels:levels,expectedClassificationSettingsRevision:catalog.classificationSettingsRevision};
    const preview=await settings.previewClassificationSettings(tenantA,patch,{manager}); assert.equal(preview.affectedApplications,1);
    await settings.updateSettings(tenantA,patch,{manager,userId});
    updated=await crud.get(app.id,{manager}); assert.equal(updated.criticality,'business_critical'); assert.equal(updated.classification_review_state,'stale');
    await assert.rejects(()=>settings.updateSettings(tenantA,patch,{manager,userId}),/changed/);
    assert.equal((await settings.getClassificationCatalog(tenantB,{manager})).classificationVersions.business,1);
    const rows=await list.list({include_inactive:true,sort:'criticality:DESC',filters:JSON.stringify({cyber_criticality:{filterType:'set',values:['critical']},business_mtd_minutes:{filterType:'number',type:'lessThanOrEqual',filter:1440}})},{manager,tenantId:tenantA});
    assert.equal(rows.total,1); assert.equal(rows.items[0].id,app.id); assert.equal(rows.items[0].classification_review_state,'stale');
    const nulls=await crud.create({name:'Unclassified'},userId,{manager});
    const sorted=await list.list({include_inactive:true,sort:'criticality:ASC'},{manager,tenantId:tenantA}); assert.equal(sorted.items.at(-1)?.id,nulls.id);
    const distinct=await list.listFilterValues({include_inactive:true,fields:'cyber_criticality,classification_review_state'},{manager,tenantId:tenantA}); assert.ok(distinct.cyber_criticality.includes(null)); assert.ok(distinct.cyber_criticality.includes('critical'));
    const expression=classificationSqlExpressions('a');
    const grouped=await manager.query(`SELECT ${expression.classification_review_state} AS state,count(*)::int AS count FROM applications a WHERE a.tenant_id=$1 GROUP BY 1`,[tenantA]); assert.equal(grouped.reduce((n:any,r:any)=>n+r.count,0),2);
    const copied=await crud.copyApplication(app.id,'Copy',userId,{manager}); assert.equal(copied.criticality,'business_critical'); assert.equal(copied.classification_review,null); assert.equal(copied.last_dr_test,null);
    const context:any={manager,tenantId:tenantA,params:{dryRun:true,mode:'replace',operation:'upsert'}};
    const csvRows:any[]=[{rowNumber:2,raw:{business_mtd_minutes:'__CLEAR__',cyber_criticality:''},parsed:{},existingEntity:updated,errors:[]}];
    await applicationCsvConfig.afterValidate!(csvRows,context); assert.deepEqual(csvRows[0].errors,[]); assert.equal(csvRows[0].parsed.criticality,null); assert.equal(csvRows[0].parsed.cyber_criticality,undefined);
    const badRows:any[]=[{rowNumber:3,raw:{criticality:'low'},parsed:{},existingEntity:updated,errors:[]}]; await applicationCsvConfig.afterValidate!(badRows,context); assert.equal(badRows[0].errors.length,1);
    const badMtdRows:any[]=[{rowNumber:4,raw:{business_mtd_minutes:'31'},parsed:{},existingEntity:updated,errors:[]}]; await applicationCsvConfig.afterValidate!(badMtdRows,context); assert.match(badMtdRows[0].errors[0].message,/tenant-configured presets/);
    const resolver = new CsvResolverService();
    const csv = new ApplicationsCsvService(manager.getRepository(Application), null as any, null as any, new CsvExportService(resolver), new CsvImportService(resolver,new CsvJsonValidators()),resolver,audit,list);
    await manager.query(`INSERT INTO application_data_residency(tenant_id,application_id,country_iso) VALUES ($1,$2,'FR')`,[tenantA,app.id]);
    const residencyRevision = Number((await manager.getRepository(Application).findOneByOrFail({id:app.id})).classification_revision);
    await crud.reviewClassification(app.id,residencyRevision,userId,{manager});
    const residencyNoopFile = {buffer:Buffer.from('name;business_mtd_minutes;data_residency\nAtlas renamed;1440;fr, FR\n'),originalname:'residency-noop.csv'} as Express.Multer.File;
    const residencyNoopDry = await csv.import(residencyNoopFile,{dryRun:true,mode:'enrich',operation:'upsert'},{manager,tenantId:tenantA,userId}); assert.equal(residencyNoopDry.ok,true,JSON.stringify(residencyNoopDry.errors));
    const residencyNoop = await csv.import(residencyNoopFile,{dryRun:false,mode:'enrich',operation:'upsert'},{manager,tenantId:tenantA,userId}); assert.equal(residencyNoop.ok,true,JSON.stringify(residencyNoop.errors));
    let residencyApp:any = await crud.get(app.id,{manager}); assert.equal(Number(residencyApp.classification_revision),residencyRevision); assert.equal(residencyApp.classification_review_state,'reviewed');
    const residencyChangeFile = {buffer:Buffer.from('name;business_mtd_minutes;data_residency\nAtlas renamed;1440;DE\n'),originalname:'residency-change.csv'} as Express.Multer.File;
    const residencyChange = await csv.import(residencyChangeFile,{dryRun:false,mode:'enrich',operation:'upsert'},{manager,tenantId:tenantA,userId}); assert.equal(residencyChange.ok,true,JSON.stringify(residencyChange.errors));
    residencyApp = await crud.get(app.id,{manager}); assert.ok(Number(residencyApp.classification_revision)>residencyRevision); assert.equal(residencyApp.classification_review_state,'stale');
    const file = {buffer:Buffer.from('name;business_mtd_minutes;cyber_criticality;recovery_wave;rpo_minutes\nCSV Atlas;30;High;vital;0\n'),originalname:'test.csv'} as Express.Multer.File;
    const dry=await csv.import(file,{dryRun:true,mode:'enrich',operation:'upsert'},{manager,tenantId:tenantA,userId}); assert.equal(dry.ok,true,JSON.stringify(dry.errors));
    const applied=await csv.import(file,{dryRun:false,mode:'enrich',operation:'upsert'},{manager,tenantId:tenantA,userId}); assert.equal(applied.ok,true,JSON.stringify(applied.errors));
    const imported=await manager.getRepository(Application).findOneByOrFail({name:'CSV Atlas',tenant_id:tenantA}); assert.equal(imported.criticality,'business_critical'); assert.equal(imported.cyber_criticality,'high'); assert.equal(imported.rpo_minutes,0);
    const exported=await csv.export({manager,tenantId:tenantA,fields:['name','business_mtd_minutes','cyber_criticality'],query:{filters:JSON.stringify({name:{filterType:'text',type:'equals',filter:'CSV Atlas'}})}}); assert.equal(exported.rowCount,1); assert.match(exported.content,/CSV Atlas/);
    const importedAudit=await manager.query("SELECT source FROM audit_log WHERE record_id=$1 AND table_name='applications'",[imported.id]); assert.ok(importedAudit.length);
    await manager.query(`SELECT set_config('app.current_tenant',$1,true)`,[tenantB]);
    await assert.rejects(()=>crud.get(app.id,{manager}),/not found/i);
    assert.equal((await list.list({include_inactive:true},{manager,tenantId:tenantB})).total,0);
    console.log('PASS: isolated PostgreSQL CRUD/review/settings/reclassification/conflict/list/rank/null/distinct/aggregate/copy/CSV residency no-op/change/tenant tests');
  } finally { await runner.rollbackTransaction(); await runner.release(); await dataSource.destroy(); }
}
main().catch(error=>{console.error(error);process.exitCode=1;});
